#### Datenvorbereitung für den Ames Housing Price Data Set und Ausgabe von CSV für folgende Modellerstellungen

###### Zweck
Hier werden zentral verschiedene CSV Dateien geschrieben, die in Skripten zur Modellerstellung eingelesen werden.
Explorative Datenanalyse wird in den Notebooks Ames EDA interaktiv.ipynb und Ames EDA * handcrafted.ipynb gemacht.

#### Besondere Funktionen : 
- Matrix der Variablen je Ausgabedatei



###### Versionsgeschichte
- 1.0 21.08.2023 Willi Hahn Initialversion 
- 1.1 21.09.2025 Willi Hahn Reduziert auf Quantifizierung von Variablen und Ausgabe von CSV.
- 1.2 06.10.2025 Willi Hahn Neue transformierte Variablen und Definition von Dimensionen
- 1.2.1 15.10.2025 Willi Hahn Ames_Num.csv ohne Ausreißer, missing values imputiert, mit allen Variablen numerisch umgewandelt. SalePriceLog, Garage area2, Overall Qual2, Overall Cond2. HouseAge, ReModAge, Neighborhood label encoded
- 1.2.2 25.10.2025 Willi Hahn Ames_NumCat.csv ohne Ausreißer, missing values imputiert. Int64 (erlaubt NaN, ist Pandas extension) umgenaut als int.
- 1.2.1 15.10.2025 Willi Hahn Abgleich der Variablen je Datei. Anpassung pandas.
- 1.3 05.10.2026 Willi Hahn BSMT_COND wenn NA, da auf Typical (statt poor) codiert. MS Subclasse, MS Zoning one hot encoded. df_numcat für Tree-Modelle.



TODO
Neue Variablen:
- RecentRemodel — Binary variable that takes 1 if YearRemodAdd >= YrSold-1
- SqYearBuilt — Continuous variable constructed by exponentiating YearBuilt to the second power
- YearSoldYearBuilt — Binary variable that takes 1 if YearBuilt = YrSold
- AgeAtSale — Continuous variable constructed by subtracting YrBuilt from YrSold
- X['AgeCond'] = X.HouseAge * X.OverallCond
- RR_Proximity — Binary variable that takes 1 if Condition1 ∈ { ‘RRNn’, ‘RRAn’, ‘RRNe’, ‘RRAe’)
- $Saleprice/sqft$/sqft Anomalie!

In [1]:
# notwendige Bibliotheken importieren und konfigurieren
import pandas as pd
_ = pd.set_option('display.max_columns', None) # damit mehr als 20 Spalten angezeigt werden.
_ = pd.set_option('display.min_rows', 16) # damit nicht nur 10 Zeilen mit  ... dazwischen ausgegeben werden
_ = pd.set_option('display.max_rows', 500) # damit nicht nur 10 Zeilen mit  ... dazwischen ausgegeben werden
from pandas.api.types import is_object_dtype
import numpy as np
import math

try:
    import google.colab
    IS_COLAB = True
    from google.colab import drive
    drive.mount('/content/drive')
    print("Google Drive gemounted!")
except ImportError:
    IS_COLAB = False

In [2]:
# Hilfsfunktionen

def add_dummies(df, columns, drop_first=False, prefix=''):
    """
    drop_first=False wird in diesem Skript immer benutzt, weil drop first manuell gemacht wird.
    Fügt Dummy-Variablen für eine Liste kategorialer Spalten hinzu, idempotent.
    Erhält die Originalvariable und erzeugt die Dummies direkt als Integer (0/1).
    
    Parameter:
    - df: pandas DataFrame
    - columns: Liste von Spaltennamen (strings), die in Dummy-Variablen umgewandelt werden sollen
    - prefix: Präfix für die Dummy-Spaltennamen (string); wenn leer, wird kein '_' verwendet
    - drop_first: Bool, ob die erste Kategorie entfernt werden soll
    
    Rückgabe:
    - df: DataFrame mit Originalspalten und neuen Dummy-Spalten (als int)
    """
    df_copy = df.copy()
    
    for col in columns:
        if col not in df_copy.columns:
            print(f"⚠️ Spalte '{col}' nicht im DataFrame gefunden. Wird übersprungen.")
            continue
            
        categories = df_copy[col].dropna().unique()
        
        # Sortieren für deterministische Ergebnisse (wichtig für drop_first)
        categories = sorted(categories)
        
        if drop_first:
            categories = categories[1:]
        
        # Dummy-Spaltennamen und Präfixe festlegen
        if prefix:
            dummy_prefix = f"{prefix}_{col}"
        else:
            dummy_prefix = col
            
        expected_cols = [f"{dummy_prefix}_{cat}" for cat in categories]
        
        # Dummies erzeugen (WICHTIG: dtype=int für 0/1 statt True/False)
        dummies = pd.get_dummies(
            df_copy[col], 
            prefix=dummy_prefix, 
            drop_first=drop_first,
            dtype=int  # <-- Das erzwingt 0 und 1
        )
        
        # Nur hinzufügen, wenn Dummy-Spalten noch nicht vorhanden sind
        if not all(col_name in df_copy.columns for col_name in expected_cols):
            # Duplikate vermeiden: Falls einzelne Dummies schon existieren, nur die fehlenden anhängen
            new_cols = [c for c in dummies.columns if c not in df_copy.columns]
            if new_cols:
                df_copy = pd.concat([df_copy, dummies[new_cols]], axis=1)
    
    return df_copy



def print_memory_usage(df, unit='MB', round_to=2):
    """
    Gibt den Gesamtspeicherverbrauch eines DataFrames aus.
    
    Parameter:
    - df: pandas DataFrame
    - unit: 'KB' oder 'MB' (Standard: 'MB')
    - round_to: Anzahl der Nachkommastellen (Standard: 2)
    
    Rückgabe:
    - Speicherverbrauch als float
    """
    factor = 1024 if unit == 'KB' else 1024**2
    usage = df.memory_usage(deep=True).sum() / factor
    print(f"Gesamtspeicherverbrauch: {usage:.{round_to}f} {unit}")
    return usage

In [3]:
# Daten einlesen 


if IS_COLAB:
    #path = '/content/drive/MyDrive/Colab Notebooks/AmesHousing.csv'
    path = 'https://raw.githubusercontent.com/WilliHahn/FHDW/main/AmesHousing.csv'
else:
    path = 'AmesHousing.csv'
#path = 'https://raw.githubusercontent.com/WilliHahn/FHDW/main/AmesHousing.csv'

df = pd.read_csv(path, sep=',') 
df_org = df.copy() # Eine Datenkopie als Referenz behalten
df_num=df.copy() # df_num vorbereiten zum Aufbau numerischer Variablen 
df_numcat=df.copy() #vorbereiten zum Aufbau für Entscheidungsbäume
#df.columns.tolist()

In [4]:
df.describe()

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,TotRms AbvGrd,Fireplaces,Garage Yr Blt,Garage Cars,Garage Area,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2930.00000,2.930000e+03,2930.000000,2440.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2907.000000,2929.000000,2929.000000,2929.000000,2929.000000,2930.000000,2930.000000,2930.000000,2930.000000,2928.000000,2928.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2771.000000,2929.000000,2929.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,1465.50000,7.144645e+08,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,442.629566,49.722431,559.262547,1051.614544,1159.557679,335.455973,4.676792,1499.690444,0.431352,0.061134,1.566553,0.379522,2.854266,1.044369,6.443003,0.599317,1978.132443,1.766815,472.819734,93.751877,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068
std,845.96247,1.887308e+08,42.638025,23.365335,7880.017759,1.411026,1.111537,30.245361,20.860286,179.112611,455.590839,169.168476,439.494153,440.615067,391.890885,428.395715,46.310510,505.508887,0.524820,0.245254,0.552941,0.502629,0.827731,0.214076,1.572964,0.647921,25.528411,0.760566,215.046549,126.361562,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357
min,1.00000,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1895.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,733.25000,5.284770e+08,20.000000,58.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,0.000000,0.000000,219.000000,793.000000,876.250000,0.000000,0.000000,1126.000000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,5.000000,0.000000,1960.000000,1.000000,320.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,1465.50000,5.354536e+08,50.000000,68.000000,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,370.000000,0.000000,466.000000,990.000000,1084.000000,0.000000,0.000000,1442.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,6.000000,1.000000,1979.000000,2.000000,480.000000,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,2197.75000,9.071811e+08,70.000000,80.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,164.000000,734.000000,0.000000,802.000000,1302.000000,1384.000000,703.750000,0.000000,1742.750000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,7.000000,1.000000,2002.000000,2.000000,576.000000,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,2930.00000,1.007100e+09,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1526.000000,2336.000000,6110.000000,5095.000000,2065.000000,1064.000000,5642.000000,3.000000,2.000000,4.000000,2.000000,8.000000,3.000000,15.000000,4.000000,2207.000000,5.000000,1488.000000,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [5]:
# Definition globaler Konstanten
# drop_first=False wird in diesem Skript immer benutzt, weil drop first manuell gemacht wird.
ONE_HOT_DROP_FIRST=False    # ACHTUNG: Unterschiedliche Modelle brauchen unterschiedliche Behandlung!
                            # In diesem Skript wird das Entfernen einer linear abhängigen Variablen jedoch manuell gemacht.

In [6]:
# Data Frame ansehen mit klassischen Methoden aus pandas

#df_num.info(verbose=True)
#df_num.info(verbose=True, show_counts=True)
###df.info(verbose=True, show_counts=True) # Namen, Datentypen und Datenanzahl not null
###print (df.describe()) # Lage-, Streuungsparameter je Variable
###df.head(20) # einfache Tabbelle mit scroll Funktion anzeichen

In [7]:
# Ausreißer entfernen
df_num = df_num[df_num['Gr Liv Area'] < 4000] # siehe Originaldoku und Ames Outlier.ipynb
df_numcat = df_numcat[df_numcat['Gr Liv Area'] < 4000] # siehe Originaldoku und Ames Outlier.ipynb

# Datenfehler beheben
df_num.loc[df_num['Order'] ==2261, 'Garage Yr Blt'] = 2007 # Datenfehler, da zuvor 2207
df_numcat.loc[df_numcat['Order'] ==2261, 'Garage Yr Blt'] = 2007 # Datenfehler, da zuvor 2207
df_num['Sale Type'] = df_num['Sale Type'].str.strip()   # Fehler mit hängendem Leerzeichen entfernen
df_numcat['Sale Type'] = df_numcat['Sale Type'].str.strip()   # Fehler mit hängendem Leerzeichen entfernen

In [8]:
# Variable SalePrice und Variablen bezogen auf den Verkauf
sale_price = pd.to_numeric(df_num['SalePrice'], errors='coerce')
df_num['SalePriceLog'] = np.log(sale_price.where(sale_price > 0)) # logarithmus naturalis. dummy zur Demonstration von data leakage.


# Anormale und Familienverkäufe entfernen
#df_num = df_num.loc[~((df_num['Sale Condition'] == 'Abnorml') | (df_num['Sale Condition'] == 'Family') )]
df_num = add_dummies(df_num, columns=['Sale Condition','Sale Type'], drop_first=ONE_HOT_DROP_FIRST)
df_numcat['Sale Condition'] = df_num['Sale Condition'].copy()
df_numcat['Sale Type'] = df_num['Sale Type'].copy()
df_num.drop(['Sale Type', 'Sale Condition'],axis=1,inplace=True)

df_num['Yr Sold'] = pd.to_numeric(df_num['Yr Sold'], errors='coerce')
df_num['Mo Sold'] = pd.to_numeric(df_num['Mo Sold'], errors='coerce')
df_numcat['Yr Sold'] = df_num['Yr Sold'].copy()
df_numcat['Mo Sold'] = df_num['Mo Sold'].copy()

# Referenz: Januar des frühesten Verkaufsjahres
ref_year = int(df_num['Yr Sold'].min())

# Monatsindex seit Referenz (0-basiert)
df_num['Sale MonthsNo'] = (
    (df_num['Yr Sold'] - ref_year) * 12 + (df_num['Mo Sold'] - 1)
)
df_numcat['Sale MonthsNo'] = df_num['Sale MonthsNo'].copy()

# 1) String "Baujahr-Monat". '2006-00' für fehlende Monate ist zwar hässlich, aber besser als ein ValueError.
mo_sold_str = df_num['Mo Sold'].fillna(0).astype(int).astype(str).str.zfill(2)
df_numcat['Sale Month'] = df_num['Yr Sold'].astype(str) + '-' + mo_sold_str

# 2) Saison + kombinierte Variable
season_map = {3:'Spring', 4:'Spring', 5:'Spring',
              6:'Summer', 7:'Summer', 8:'Summer',
              9:'Autumn', 10:'Autumn', 11:'Autumn',
              12:'Winter', 1:'Winter', 2:'Winter'}

df_numcat['Sale Season'] = df_num['Yr Sold'].astype(str) + '-' + df_num['Mo Sold'].astype(int).map(season_map)  # .astype(int).astype(str).str.zfill(2))

In [9]:
# Variablen bezogen auf Lage und Gründstück

# Kategoriale Sicherung VOR dem Mapping
for col in ['Lot Shape', 'Land Slope', 'Land Contour', 'Lot Config']:
    df_numcat[col] = df_num[col].copy()

# Jetzt die numerischen Mappings (wie gehabt)
df_num['Lot Shape'] = df_num['Lot Shape'].map(
    {'Reg': 5, 'IR1': 2, 'IR2': 1, 'IR3': 0}
).astype('Int64')
df_num['Land Slope'] = df_num['Land Slope'].map(
    {'Gtl': 5, 'Mod': 2, 'Sev': 0}
).astype('Int64')
df_num['Land Contour'] = df_num['Land Contour'].map(
    {'Lvl': 5, 'Bnk': 2, 'Low': 2, 'HLS': 1}
).astype('Int64')
df_num['Lot Config'] = df_num['Lot Config'].map(
    {'CulDSac': 4, 'Inside': 3, 'Corner': 2, 'FR2': 1, 'FR3': 1}
).astype('Int64')

# Imputation der Lot Frontage / Gebäudefront mit dem Mittelwert der Nachbarschaft
df_num["Lot Frontage"] = pd.to_numeric(df_num["Lot Frontage"], errors='coerce', downcast="float")

# Mittelwert je Neighborhood
neighborhood_means = df_num.groupby('Neighborhood')['Lot Frontage'].mean()
neighborhood_means = neighborhood_means.fillna(neighborhood_means.mean())

# Fehlende Werte durch Neighborhood-Mittelwert ersetzen (vektorisiert, kein map)
df_num['Lot Frontage'] = (
    df_num['Lot Frontage']
    .fillna(df_num['Neighborhood'].map(neighborhood_means))
)

# Fallback: immer noch NaN (z. B. Neighborhood unbekannt) → globaler Mittelwert
df_num['Lot Frontage'] = df_num['Lot Frontage'].fillna(neighborhood_means.mean())

df_numcat['Lot Frontage'] = df_num['Lot Frontage'].copy()

# Berechne den Median pro Neighborhood für neue Variable NeighborhoodClass
# Achtung: NeighborhoodClass nutzt SalePrice → Target Leakage!
median_prices = df_num.groupby('Neighborhood')['SalePrice'].median()
neighborhood_class = median_prices.apply(
    lambda x: 1 if x < 145000 else (2 if x < 290000 else 3)
)

df_num['NeighborhoodClass'] = df_num['Neighborhood'].map(neighborhood_class)
df_numcat['NeighborhoodClass'] = df_num['NeighborhoodClass'].astype(str).copy()

# 1) Neighbor_int VOR dem Dummien
codes, unique = pd.factorize(df_num['Neighborhood'])
df_num['Neighbor_int'] = codes

# 2) Neighbor_intsorted VOR dem Dummien
mean_price_per_neigh = df_num.groupby('Neighborhood')['SalePrice'].mean().sort_values()
rank_mapping = {neigh: idx + 1 for idx, neigh in enumerate(mean_price_per_neigh.index)}
df_num['Neighbor_intsorted'] = df_num['Neighborhood'].map(rank_mapping)

# 3) Jetzt erst df_numcat sichern und dummien
df_numcat['Neighborhood'] = df_num['Neighborhood'].copy()
df_num = add_dummies(df_num, columns=['Neighborhood'], drop_first=ONE_HOT_DROP_FIRST)
df_num.drop(['Neighborhood'], axis=1, inplace=True)

df_numcat['MS Zoning'] = df_num['MS Zoning'].copy()
df_num = add_dummies(df_num, columns=['MS Zoning'], drop_first=ONE_HOT_DROP_FIRST)
df_num.drop(['MS Zoning'],axis=1,inplace=True)

# Alle Condition-Werte zusammen betrachten
cond1 = df_num['Condition 1'].fillna('').astype(str)
cond2 = df_num['Condition 2'].fillna('').astype(str)
# Ist das Haus an einer Straße?
df_num['IsOnArtery'] = ((cond1 == 'Artery') | (cond2 == 'Artery')).astype(int)
df_num['IsOnFeedr']  = ((cond1 == 'Feedr')  | (cond2 == 'Feedr')).astype(int)
df_num['IsOnMainRoad']   = ((cond1.isin(['Artery', 'Feedr'])) |(cond2.isin(['Artery', 'Feedr']))).astype(int)
df_numcat['IsOnArtery']= df_num['IsOnArtery'].copy()
df_numcat['IsOnFeedr'] = df_num['IsOnFeedr'].copy() 
df_numcat['IsOnMainRoad']  = df_num['IsOnMainRoad'].copy()  
 
df_num['IsNearRailroad'] = (    cond1.str.startswith('RR') | cond2.str.startswith('RR')).astype(int)
df_num['IsAdjacentRailroad'] = (    cond1.isin(['RRAn', 'RRAe']) | cond2.isin(['RRAn', 'RRAe'])).astype(int)
df_numcat['IsNearRailroad'] = df_num['IsNearRailroad'].copy()
df_numcat['IsAdjacentRailroad'] = df_num['IsAdjacentRailroad'].copy() 

# Ist das Haus an einem positiven Merkmal?
df_num['IsNearPositive'] = (    cond1.str.startswith('PosN') | cond2.str.startswith('PosN')).astype(int)
df_num['IsAdjacentPositive'] = (    cond1.isin(['PosA']) | cond2.isin(['PosA'])).astype(int)
df_numcat['IsNearPositive'] = df_num['IsNearPositive'].copy()
df_numcat['IsAdjacentPositive'] = df_num['IsAdjacentPositive'].copy()

df_numcat['Condition 1'] = df_num['Condition 1'].copy()
df_numcat['Condition 2'] = df_num['Condition 2'].copy()
df_num.drop(['Condition 1', 'Condition 2'],axis=1,inplace=True) # 


df_numcat['Street'] = df_num['Street'].copy() 
df_num = add_dummies(df_num, columns=['Street'], drop_first=ONE_HOT_DROP_FIRST)
df_num.drop(['Street'],axis=1,inplace=True) 

df_numcat['Paved Drive'] = df_num['Paved Drive'].copy()
df_num['Paved Drive'] = df_num['Paved Drive'].map({'N': 0, 'P': 1, 'Y': 2}).fillna(-1).astype('int')

df_num['Alley'] = df_num['Alley'].fillna('None')
df_numcat['Alley'] = df_num['Alley'].copy()
df_num['Alley'] = df_num['Alley'].map({'Pave':3, 'Grvl':2, 'None':0, 'NA':0, '':0, 'nan':0})
df_num['Alley'] = df_num['Alley'].fillna(0).astype('int')   # Fallback für unbekannte
df_num['HasAlley'] = (df_num['Alley'] != 0).astype(int)
df_numcat['HasAlley'] = df_num['HasAlley'].copy()

In [10]:
## Variablen bezogen auf das Haus und dessen Innen- und Aussenausstattung

# ============================================================
# MS SubClass: numerische Codes in Kategorien umwandeln
ms_subclass_labels = {
     20: '1Story_1946_newer',
     30: '1Story_1945_older',
     40: '1Story_finished_attic',
     45: '1.5Story_unfinished',
     50: '1.5Story_finished',
     60: '2Story_1946_newer',
     70: '2Story_1945_older',
     75: '2.5Story',
     80: 'Split_MultiLevel',
     85: 'Split_Foyer',
     90: 'Duplex',
    120: '1Story_PUD_1946_newer',
    150: '1.5Story_PUD',
    160: '2Story_PUD_1946_newer',
    180: 'PUD_MultiLevel',
    190: '2Family_Conversion'
}

ms_subclass_stories = {
     20: '1 Story',
     30: '1 Story',
     40: '1 Story',
    120: '1 Story',
     45: '1.5 Story',
     50: '1.5 Story',
    150: '1.5 Story',
     60: '2 Story',
     70: '2 Story',
    160: '2 Story',
     75: '2 Story', # '2.5Story',
     80: 'MultiLevel',   # ggf. zu '2Story' oder eigener Kategorie
     85: 'MultiLevel',
     90: 'MultiLevel',  #'Duplex',       # ggf. eigene Kategorie
    180: 'MultiLevel',
    190: 'MultiLevel', # '2Family'       # ggf. eigene Kategorie
}

df_numcat['MS SubClass Stories'] = df_num['MS SubClass'].map(ms_subclass_stories)


# Neue kategoriale Variable erzeugen
df_num['MS SubClass_num'] = df_num['MS SubClass'].astype(int)
df_num['MS SubClass'] = df_num['MS SubClass'].map(ms_subclass_labels)
df_num = add_dummies(df_num, columns=['MS SubClass'], drop_first=ONE_HOT_DROP_FIRST)
df_numcat['MS SubClass'] = df_num['MS SubClass'].copy()
df_num.drop(['MS SubClass'],axis=1,inplace=True)

gr_liv = pd.to_numeric(df_num['Gr Liv Area'], errors='coerce')
df_num['Gr Liv Area Log'] = np.log(gr_liv.where(gr_liv > 0))
df_num['Gr Liv Area2'] = gr_liv ** 2

df_num['Area1st2nd'] = df_num['1st Flr SF'] + df_num['2nd Flr SF']
df_numcat['Area1st2nd'] = df_num['Area1st2nd'].copy()
df_num['Has2ndfloor'] = (pd.to_numeric(df_num['2nd Flr SF'], errors='coerce').fillna(0) > 0).astype(int)
df_numcat['Has2ndfloor'] = df_num['Has2ndfloor'].copy() 

df_num['Overall Qual2'] = df_num['Overall Qual'] ** 2
df_num['Overall Cond2'] = df_num['Overall Cond'] ** 2
df_num['Misc Feature'] = df_num['Misc Feature'].fillna('NA')
df_numcat['Misc Feature'] = df_num['Misc Feature'].copy()
df_num = add_dummies(df_num, columns=['Misc Feature'], drop_first=ONE_HOT_DROP_FIRST)
df_num.drop(['Misc Feature'],axis=1,inplace=True)

df_num['Utilities'] = df_num['Utilities'].fillna('None')
df_num['Utilities'] = df_num['Utilities'].map({'AllPub':3,'NoSewr':1,'NoSeWa':1,'ELO':0,'None':0}).fillna(0).astype('int')
df_num['Kitchen Bsmt'] = (
    (df_num['Kitchen AbvGr'] == 0) &
    (df_num['Kitchen Qual'].astype(str).str.strip().isin(
        ['Ex', 'Gd', 'TA', 'Fa', 'Po']
    ))
).astype(int)
df_numcat['Kitchen Bsmt'] = df_num['Kitchen Bsmt'].copy()
for i in ['Exter Qual','Exter Cond','Kitchen Qual']:
    df_num[i] = df_num[i].map({'Ex':4,'Gd':3,'TA':2,'Fa':1,'Po':0}).fillna(0).astype('int')

df_num = add_dummies(df_num, columns=['Heating'], drop_first=ONE_HOT_DROP_FIRST)
df_numcat['Heating'] = df_num['Heating'].copy()
df_num.drop(['Heating'], axis=1, inplace=True)
df_numcat['Heating QC'] = df_num['Heating QC'].copy()
df_num['Heating QC'] = df_num['Heating QC'].map({'Ex':4,'Gd':3,'TA':2,'Fa':1,'Po':0}).fillna(0).astype('int')

df_numcat['Central Air'] = df_num['Central Air'].copy()
df_num['Central Air'] = df_num['Central Air'].map(    {'Y': 1, 'N': 0}).fillna(0).astype(int)

df_num['Electrical'] = df_num['Electrical'].fillna('SBrkr')  # Imputation von 1 missing value mit dem MOdus
df_numcat['Electrical'] = df_num['Electrical'].copy()
df_num['Electrical'] = df_num['Electrical'].map({'SBrkr':5,'FuseA':4,'FuseF':3, 'FuseP':2, 'Mix':1, 'NA':0, 'None':0}).fillna(0).astype('int')

df_num['Fireplace Qu'] = df_num['Fireplace Qu'].fillna('None')
df_numcat['Fireplace Qu'] = df_num['Fireplace Qu'].copy()
df_num['Fireplace Qu'] = df_num['Fireplace Qu'].map({'Ex':5,'Gd':4,'TA':3,'Fa':2,'Po':1,'None':0,'NA':0}).fillna(0).astype('int')
df_num['HasFireplace'] = (  pd.to_numeric(df_num['Fireplaces'], errors='coerce').fillna(0) > 0 ).astype(int)
df_numcat['HasFireplace'] = df_num['HasFireplace'].copy() 

df_num['Pool QC'] = df_num['Pool QC'].fillna('None')
pool_qc_categories = ['None', 'Po', 'Fa', 'TA', 'Gd', 'Ex']
df_numcat['Pool QC'] = pd.Categorical(df_num['Pool QC'], categories=pool_qc_categories, ordered=True)
df_num['Pool QC'] = df_num['Pool QC'].map({'Ex':4,'Gd':3,'TA':2,'Fa':1,'None':0,'NA':0}).fillna(0).astype('int')
df_num['HasPool'] = ( pd.to_numeric(df_num['Pool Area'], errors='coerce').fillna(0) > 0 ).astype(int)
df_numcat['HasPool'] = df_num['HasPool'].copy()

df_num['Fence'] = df_num['Fence'].fillna('None')
df_numcat['Fence'] = df_num['Fence'].copy()
df_num['Fence'] = df_num['Fence'].map({'GdPrv':4,'GdWo':3,'MnPrv':2,'MnWw':1,'None':0,'NA':0}).fillna(0).astype('int')
df_num['HasFence'] = (df_num['Fence'] != 0).astype(int)
df_numcat['HasFence'] = df_num['HasFence'].copy()

# Wenn Exterior 2nd == Exterior 1st → 'None'
df_num['Exterior 2nd'] = df_num['Exterior 2nd'].where(
    df_num['Exterior 2nd'] != df_num['Exterior 1st'],
    'None'
)
df_numcat['Exterior 1st'] = df_num['Exterior 1st'].copy()
df_numcat['Exterior 2nd'] = df_num['Exterior 2nd'].copy()

df_num = add_dummies(
    df_num,
    columns=['Exterior 1st'],
    drop_first=False,
)

df_num = add_dummies(
    df_num,
    columns=['Exterior 2nd'],
    drop_first=False,
)
df_num.drop(['Exterior 1st', 'Exterior 2nd'],axis=1,inplace=True) # 




df_num['Mas Vnr Type'] = df_num['Mas Vnr Type'].fillna('None')
df_numcat['Mas Vnr Type'] = df_num['Mas Vnr Type'].copy()
df_num = add_dummies(df_num, columns=['Mas Vnr Type'], drop_first=ONE_HOT_DROP_FIRST)
df_num.drop(['Mas Vnr Type'],axis=1,inplace=True) 
df_num["Mas Vnr Area"] = pd.to_numeric(df_num["Mas Vnr Area"], errors='coerce', downcast="float")
df_num['Mas Vnr Area'] = df_num['Mas Vnr Area'].fillna(0)
df_numcat['Mas Vnr Area'] = df_num['Mas Vnr Area'].copy()
df_num['HasMasVnr'] = (    pd.to_numeric(df_num['Mas Vnr Area'], errors='coerce').fillna(0) > 0 ).astype(int)
df_numcat['HasMasVnr'] = df_num['HasMasVnr'].copy()

df_num = add_dummies(df_num, columns=['House Style', 'Bldg Type', 'Foundation'], drop_first=ONE_HOT_DROP_FIRST)
df_numcat['House Style'] = df_num['House Style'].copy()
df_numcat['Bldg Type'] = df_num['Bldg Type'].copy()
df_numcat['Foundation'] = df_num['Foundation'].copy()
df_num.drop(['Bldg Type', 'House Style', 'Foundation'],axis=1,inplace=True)

df_num['HouseAge'] = df_num['Yr Sold'] - df_num['Year Built'].astype('int')
df_numcat['HouseAge'] = df_num['HouseAge'].copy()
df_num['HouseRemodelAge'] = df_num['Yr Sold'] - df_num['Year Remod/Add'].astype('int')
df_numcat['HouseRemodelAge'] = df_num['HouseRemodelAge'].copy()
df_num['HouseIsRemodeled'] = np.where(df_num['Year Remod/Add']  == df_num['Year Built'], 0, 1)
df_numcat['HouseIsRemodeled'] = df_num['HouseIsRemodeled'].copy()
df_num['HouseIsNew'] =  np.where(df_num['Yr Sold'] == df_num['Year Built'], 1, 0)
df_numcat['HouseIsNew']  = df_num['HouseIsNew'] .copy()
# Bedingungen für RenovationNeeded definieren
CONDITIONS = {
    # String-Spalten (noch nicht gemappt)
    'Functional':      lambda x: x.isin(['Sal', 'Sev', 'Maj2']),
    'Paved Drive':     lambda x: x == 'N',
    'Exterior 1st':    lambda x: x == 'AsbShng',      # existiert nicht mehr → skip
    'Exterior 2nd':    lambda x: x == 'AsbShng',      # existiert nicht mehr → skip

    # Numerische Spalten (bereits gemappt) – gegen Zahlen prüfen
    'Bsmt Cond':       lambda x: pd.to_numeric(x, errors='coerce').isin([1, 2]),
    'Electrical':      lambda x: pd.to_numeric(x, errors='coerce') == 2,   # FuseP = 2
    'Exter Qual':      lambda x: pd.to_numeric(x, errors='coerce').isin([0, 1]),
    'Fireplace Qu':    lambda x: pd.to_numeric(x, errors='coerce').isin([1, 2]),
    'Garage Cond':     lambda x: pd.to_numeric(x, errors='coerce').isin([1, 2]),
    'Garage Qual':     lambda x: pd.to_numeric(x, errors='coerce').isin([1, 2]),
    'Heating QC':      lambda x: pd.to_numeric(x, errors='coerce').isin([0, 1]),
    'Kitchen Qual':    lambda x: pd.to_numeric(x, errors='coerce').isin([0, 1]),
    'Pool QC':         lambda x: pd.to_numeric(x, errors='coerce') == 1,   # Fa = 1
    'Utilities':       lambda x: pd.to_numeric(x, errors='coerce').isin([0, 1]),
    'Low Qual Fin SF': lambda x: pd.to_numeric(x, errors='coerce') > 100,
    'Overall Cond':    lambda x: pd.to_numeric(x, errors='coerce').isin([1, 2]),
    'Overall Qual':    lambda x: pd.to_numeric(x, errors='coerce').isin([0, 1, 2]),
}

# Erstelle die RenovationNeeded-Spalte
mask = pd.Series(False, index=df_num.index)
for col, condition_func in CONDITIONS.items():
    if col in df.columns:
        try:
            condition_mask = condition_func(df_num[col].fillna(''))
            mask = mask | condition_mask
        except Exception as e:
            print(f"Fehler bei Spalte {col}: {e}")
            continue
df_num['RenovationNeeded'] = mask.astype(int)

df_num['Bsmt Full Bath'] = df_num['Bsmt Full Bath'].fillna(0)
df_num['Bsmt Half Bath'] = df_num['Bsmt Half Bath'].fillna(0)
df_num["Bsmt Full Bath"] = pd.to_numeric(df_num["Bsmt Full Bath"], errors='coerce', downcast="float")
df_num["Bsmt Half Bath"] = pd.to_numeric(df_num["Bsmt Half Bath"], errors='coerce', downcast="float")
df_num['BathroomsTotal'] = df_num['Full Bath'] + df_num['Bsmt Full Bath'] + 0.5 * df_num['Bsmt Half Bath'] + 0.5 * df_num['Half Bath'] 
df_num['BathroomsTotal'] = df_num['BathroomsTotal'].fillna(0)
df_numcat['BathroomsTotal'] = df_num['BathroomsTotal'].copy()

df_numcat['Functional'] = df_num['Functional'].copy() 
df_num['Functional'] = df_num['Functional'].map({'Typ':7,'Min1':6,'Min2':5,'Mod':4,'Maj1':3,'Maj2':2,'Sev':1,'Sal':0})

df_num['PorchSFTotal'] = ( df_num['Wood Deck SF'] + df_num['Open Porch SF'] + df_num['Enclosed Porch'] +
                           df_num['3Ssn Porch'] + df_num['Screen Porch'] )
df_numcat['PorchSFTotal'] = df_num['PorchSFTotal'].copy()
porch_cols = ['Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch', 'Screen Porch']
df_num['HasPorch'] = (df_num[porch_cols].apply(pd.to_numeric, errors='coerce').fillna(0).sum(axis=1) > 0).astype(int)
df_numcat['HasPorch'] = df_num['HasPorch'].copy()

Fehler bei Spalte Exterior 1st: 'Exterior 1st'
Fehler bei Spalte Exterior 2nd: 'Exterior 2nd'

In [11]:
## Variablen bezogen auf Dach und Dachausbau
df_numcat['Roof Matl'] = df_num['Roof Matl'].copy()
df_numcat['Roof Style'] = df_num['Roof Style'].copy()
df_num = add_dummies(df_num, columns=['Roof Matl', 'Roof Style'], drop_first=ONE_HOT_DROP_FIRST)
df_num.drop(['Roof Style', 'Roof Matl'],axis=1,inplace=True)

In [12]:
## Variablen bezogen auf den Keller

# ==================================================
# 1. Numerische SF-Spalten
# ==================================================

for col in ['BsmtFin SF 1', 'BsmtFin SF 2', 'Bsmt Unf SF']:
    df_num[col] = pd.to_numeric(df_num[col], errors='coerce')

# ==================================================
# 2. BsmtFin Type 1/2 — ordinal
#    Ames-Konvention: 'No' = kein Keller
# ==================================================

for col in ['BsmtFin Type 1', 'BsmtFin Type 2']:
    df_num[col] = df_num[col].fillna('No')
    df_numcat[col] = df_num[col].copy()
    df_num[col] = df_num[col].map(
        {'NA': 0, 'None': 0, 'No': 0, 'Unf': 1, 'LwQ': 2, 'Rec': 3, 'BLQ': 4, 'ALQ': 5, 'GLQ': 6}
    ).fillna(0).astype('int')

# ==================================================
# 3. Fehlende Werte in SF-Spalten
# ==================================================

df_num['BsmtFin SF 1'] = df_num['BsmtFin SF 1'].fillna(0)
df_num['BsmtFin SF 2'] = df_num['BsmtFin SF 2'].fillna(0)
df_num['Bsmt Unf SF']  = df_num['Bsmt Unf SF'].fillna(0)

# ==================================================
# 4. Total Bsmt SF — Original gegen berechnete Summe prüfen
#    (NICHT überschreiben: Ames-Original enthält echte Information)
# ==================================================
# Total Bsmt SF: NaN in df_numcat durch 0 ersetzen,
# weil "kein Keller" semantisch = 0 sqft entspricht.
df_num['Total Bsmt SF'] = (
    pd.to_numeric(df_num['Total Bsmt SF'], errors='coerce')
      .fillna(0)
      .copy()
)
df_numcat['Total Bsmt SF']   = df_num['Total Bsmt SF'].copy()

# ==================================================
# 5. Kategoriale Sicherung
# ==================================================

df_numcat['Bsmt Unf SF']   = df_num['Bsmt Unf SF'].copy()
df_numcat['BsmtFin SF 1']  = df_num['BsmtFin SF 1'].copy()
df_numcat['BsmtFin SF 2']  = df_num['BsmtFin SF 2'].copy()



# ==================================================
# 6. Bäder
# ==================================================

df_num['Bsmt Full Bath'] = df_num['Bsmt Full Bath'].fillna(0)
df_num['Bsmt Half Bath'] = df_num['Bsmt Half Bath'].fillna(0)
df_numcat['Bsmt Full Bath'] = df_num['Bsmt Full Bath'].copy()
df_numcat['Bsmt Half Bath'] = df_num['Bsmt Half Bath'].copy()

# ==================================================
# 7. Bsmt Qual / Bsmt Cond — ordinal
#    Ames-Konvention: 'No' = kein Keller
# ==================================================

for col in ['Bsmt Qual', 'Bsmt Cond']:
    df_num[col] = df_num[col].fillna('No')
    df_numcat[col] = df_num[col].copy()
    df_num[col] = df_num[col].map(
        {'Ex':5, 'Gd':4, 'TA':3, 'Fa':2, 'Po':1, 'No':0, 'NA':0, 'None':0}
    ).astype('int')

# ==================================================
# 8. Bsmt Exposure — ordinal
# ==================================================

df_num['Bsmt Exposure'] = df_num['Bsmt Exposure'].fillna('No')
df_num['Bsmt Exposure'] = df_num['Bsmt Exposure'].map(
    {'Gd':3, 'Av':2, 'Mn':1, 'No':0, 'NA':0, 'None':0}
).fillna(0).astype('int')
df_numcat['Bsmt Exposure'] = df_num['Bsmt Exposure'].copy()

# ==================================================
# 9. HasBsmt — Keller vorhanden?
# ==================================================

df_num['HasBsmt'] = (df_num['Bsmt Qual'] > 0).astype(int)
df_numcat['HasBsmt'] = df_num['HasBsmt'].copy()

In [13]:
# Garage-Variablen — korrekt für lineare Regression und Decision Trees
#   mit -1-Sentinel für Garage Yr Blt

# ==================================================
# 1. Garage Type
# ==================================================

df_num['Garage Type'] = df_num['Garage Type'].fillna('missing')
df_numcat['Garage Type'] = df_num['Garage Type'].copy()

no_garage  = df_num['Garage Type'] == 'missing'
has_garage = ~no_garage

# ==================================================
# 2. Garage Finish
# ==================================================

df_num['Garage Finish'] = df_num['Garage Finish'].fillna('missing')
df_numcat['Garage Finish'] = df_num['Garage Finish'].copy()
df_num['Garage Finish'] = df_num['Garage Finish'].map(
    {'Fin': 3, 'RFn': 2, 'Unf': 1, 'No': 0, 'NA': 0, 'None': 0, 'missing': 0}
).fillna(0).astype(int)

# ==================================================
# 3. Garage Qual / Cond
# ==================================================

for col in ['Garage Qual', 'Garage Cond']:
    df_num[col] = df_num[col].fillna('missing')
    df_numcat[col] = df_num[col].copy()
    df_num[col] = df_num[col].map(
        {'Ex': 5, 'Gd': 4, 'TA': 3, 'Fa': 2, 'Po': 1, 'No': 0, 'NA': 0, 'None': 0, 'missing': 0}
    ).fillna(0).astype(int)

# ==================================================
# 4. Garage Yr Blt — Sentinel -1 für Häuser ohne Garage
#    WICHTIG: GarageAge muss VOR dem Sentinel berechnet werden!
# ==================================================

df_num['Garage Yr Blt'] = pd.to_numeric(df_num['Garage Yr Blt'], errors='coerce')

# Für Häuser MIT Garage: fehlendes Baujahr durch Year Built ersetzen
df_num.loc[has_garage, 'Garage Yr Blt'] = (
    df_num.loc[has_garage, 'Garage Yr Blt']
    .fillna(df_num.loc[has_garage, 'Year Built'])
)

# Für Häuser OHNE Garage: vorerst NaN lassen (NICHT -1!)
# → damit GarageAge gleich korrekt berechnet werden kann
df_num.loc[no_garage, 'Garage Yr Blt'] = np.nan


# ==================================================
# 6. GarageAge — aus NaN-Version berechnen, DANN beide Spalten füllen
#    df_num    → GarageAge = 0   (lineare Regression)
#    df_numcat → GarageAge = -1  (Decision Tree)
# ==================================================

# GarageAge = 0 in df_num bedeutet "keine Garage ODER Garage im selben Jahr gebaut".
# Die Unterscheidung erfolgt über HasGarage.
garage_age_raw = df_num['Yr Sold'] - df_num['Garage Yr Blt']  # NaN für Häuser ohne Garage

df_num['GarageAge']    = garage_age_raw.fillna(0).astype(int)   # Für lineare Regression
df_numcat['GarageAge'] = garage_age_raw.fillna(-1).astype(int).copy()  # Für Decision Tree

# ==================================================
# 7. Garage Yr Blt — JETZT Sentinel -1 setzen (nach GarageAge!) 
#  Achtung: Berechnung von Korrelation muss den Sentinel filtern.
# ==================================================

df_num['Garage Yr Blt'] = df_num['Garage Yr Blt'].fillna(-1).astype(int)
df_numcat['Garage Yr Blt'] = (
    df_num['Garage Yr Blt']
    .replace(-1, 'keine Garage')
    .astype(str)
    .copy()
)
# ==================================================
# 8. Garage Cars
# ==================================================

df_num['Garage Cars'] = pd.to_numeric(
    df_num['Garage Cars'], errors='coerce'
).fillna(0).astype(int)
df_numcat['Garage Cars'] = df_num['Garage Cars'].copy()

# ==================================================
# 9. Garage Area
# ==================================================

df_num['Garage Area'] = pd.to_numeric(
    df_num['Garage Area'], errors='coerce'
).fillna(0)
df_numcat['Garage Area'] = df_num['Garage Area'].copy()
df_num['Garage Area2'] = df_num['Garage Area'] ** 2

# ==================================================
# 10. HasGarage & GarageFor2PlusCars
df_num['HasGarage'] = (  has_garage | (df_num['Garage Area'] > 0) ).astype(int)
df_numcat['HasGarage'] = df_num['HasGarage'].copy()

df_num['GarageFor2PlusCars'] = (df_num['Garage Cars'] >= 2).astype(int)
df_numcat['GarageFor2PlusCars'] = df_num['GarageFor2PlusCars'].copy()

# ==================================================
# 11. One-Hot-Encoding Garage Type
# ==================================================

df_numcat['Garage Type'] = df_num['Garage Type'].copy()
df_num = add_dummies(df_num, columns=['Garage Type'], drop_first=ONE_HOT_DROP_FIRST)
df_num.drop(['Garage Type'],axis=1,inplace=True)

In [14]:
# Variablen entfernen. Für df_numcat und LightGBM categorical vars konvertieren.

# Spalte Order bleibt, weil  als eindeutiger Schlüssel verwendet. besonders zur Anzeige in interaktiven plot. Order muss bei Modellbildung entfernt werden.
#df_num.drop('PID',axis=1,inplace=True) 
#df_numcat.drop('PID',axis=1,inplace=True) 
#df_num.drop(['Functional'],axis=1,inplace=True) 


# Für LightGBM: Alle object- oder StringDtype-Spalten in category konvertieren
for col in df_numcat.select_dtypes(include=['object', 'string']).columns:
    df_numcat[col] = df_numcat[col].astype('category').copy()

In [15]:
# letzter Check der Variablen mit df.info
#df_num.info(verbose=True, show_counts=True, memory_usage='deep')
#df_numcat.info(verbose=True,  show_counts=True, memory_usage='deep')

In [16]:
# Hilfsausgabe, um die vorhandenen Variablen durch Copy&paste bei .to_csv einzufügen.

# Numerische Spalten extrahieren
sorted_columns = sorted(df_num.select_dtypes(include='number').columns.tolist())
# alle Variablen
sorted_columns = sorted(df_num.columns.tolist())
# Spalten in Gruppen zu je 6 Elementen aufteilen
for i in range(0, len(sorted_columns), 6):
    chunk = sorted_columns[i:i+6]
    quoted_chunk = [f"'{col}'" for col in chunk]
    print(', '.join(quoted_chunk)+ ',')

print()

sorted_columns_cat = sorted(df_numcat.columns.tolist())
print(f"# df_numcat: {len(sorted_columns_cat)} Spalten")
print("# " + "=" * 60)
for i in range(0, len(sorted_columns_cat), 6):
    chunk = sorted_columns_cat[i:i+6]
    quoted_chunk = [f"'{col}'" for col in chunk]
    print(', '.join(quoted_chunk) + ',')

'1st Flr SF', '2nd Flr SF', '3Ssn Porch', 'Alley', 'Area1st2nd', 'BathroomsTotal',
'Bedroom AbvGr', 'Bldg Type_1Fam', 'Bldg Type_2fmCon', 'Bldg Type_Duplex', 'Bldg Type_Twnhs', 'Bldg Type_TwnhsE',
'Bsmt Cond', 'Bsmt Exposure', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Bsmt Qual', 'Bsmt Unf SF',
'BsmtFin SF 1', 'BsmtFin SF 2', 'BsmtFin Type 1', 'BsmtFin Type 2', 'Central Air', 'Electrical',
'Enclosed Porch', 'Exter Cond', 'Exter Qual', 'Exterior 1st_AsbShng', 'Exterior 1st_AsphShn', 'Exterior 1st_BrkComm',
'Exterior 1st_BrkFace', 'Exterior 1st_CBlock', 'Exterior 1st_CemntBd', 'Exterior 1st_HdBoard', 'Exterior 1st_ImStucc', 'Exterior 1st_MetalSd',
'Exterior 1st_Plywood', 'Exterior 1st_PreCast', 'Exterior 1st_Stone', 'Exterior 1st_Stucco', 'Exterior 1st_VinylSd', 'Exterior 1st_Wd Sdng',
'Exterior 1st_WdShing', 'Exterior 2nd_AsbShng', 'Exterior 2nd_AsphShn', 'Exterior 2nd_Brk Cmn', 'Exterior 2nd_BrkFace', 'Exterior 2nd_CBlock',
'Exterior 2nd_CmentBd', 'Exterior 2nd_HdBoard', 'Exterior 2nd_ImStucc', 'Exterior 2nd_MetalSd', 'Exterior 2nd_None', 'Exterior 2nd_Other',
'Exterior 2nd_Plywood', 'Exterior 2nd_Stone', 'Exterior 2nd_Stucco', 'Exterior 2nd_VinylSd', 'Exterior 2nd_Wd Sdng', 'Exterior 2nd_Wd Shng',
'Fence', 'Fireplace Qu', 'Fireplaces', 'Foundation_BrkTil', 'Foundation_CBlock', 'Foundation_PConc',
'Foundation_Slab', 'Foundation_Stone', 'Foundation_Wood', 'Full Bath', 'Functional', 'Garage Area',
'Garage Area2', 'Garage Cars', 'Garage Cond', 'Garage Finish', 'Garage Qual', 'Garage Type_2Types',
'Garage Type_Attchd', 'Garage Type_Basment', 'Garage Type_BuiltIn', 'Garage Type_CarPort', 'Garage Type_Detchd', 'Garage Type_missing',
'Garage Yr Blt', 'GarageAge', 'GarageFor2PlusCars', 'Gr Liv Area', 'Gr Liv Area Log', 'Gr Liv Area2',
'Half Bath', 'Has2ndfloor', 'HasAlley', 'HasBsmt', 'HasFence', 'HasFireplace',
'HasGarage', 'HasMasVnr', 'HasPool', 'HasPorch', 'Heating QC', 'Heating_Floor',
'Heating_GasA', 'Heating_GasW', 'Heating_Grav', 'Heating_OthW', 'Heating_Wall', 'House Style_1.5Fin',
'House Style_1.5Unf', 'House Style_1Story', 'House Style_2.5Fin', 'House Style_2.5Unf', 'House Style_2Story', 'House Style_SFoyer',
'House Style_SLvl', 'HouseAge', 'HouseIsNew', 'HouseIsRemodeled', 'HouseRemodelAge', 'IsAdjacentPositive',
'IsAdjacentRailroad', 'IsNearPositive', 'IsNearRailroad', 'IsOnArtery', 'IsOnFeedr', 'IsOnMainRoad',
'Kitchen AbvGr', 'Kitchen Bsmt', 'Kitchen Qual', 'Land Contour', 'Land Slope', 'Lot Area',
'Lot Config', 'Lot Frontage', 'Lot Shape', 'Low Qual Fin SF', 'MS SubClass_1.5Story_PUD', 'MS SubClass_1.5Story_finished',
'MS SubClass_1.5Story_unfinished', 'MS SubClass_1Story_1945_older', 'MS SubClass_1Story_1946_newer', 'MS SubClass_1Story_PUD_1946_newer', 'MS SubClass_1Story_finished_attic', 'MS SubClass_2.5Story',
'MS SubClass_2Family_Conversion', 'MS SubClass_2Story_1945_older', 'MS SubClass_2Story_1946_newer', 'MS SubClass_2Story_PUD_1946_newer', 'MS SubClass_Duplex', 'MS SubClass_PUD_MultiLevel',
'MS SubClass_Split_Foyer', 'MS SubClass_Split_MultiLevel', 'MS SubClass_num', 'MS Zoning_A (agr)', 'MS Zoning_C (all)', 'MS Zoning_FV',
'MS Zoning_I (all)', 'MS Zoning_RH', 'MS Zoning_RL', 'MS Zoning_RM', 'Mas Vnr Area', 'Mas Vnr Type_BrkCmn',
'Mas Vnr Type_BrkFace', 'Mas Vnr Type_CBlock', 'Mas Vnr Type_None', 'Mas Vnr Type_Stone', 'Misc Feature_Gar2', 'Misc Feature_NA',
'Misc Feature_Othr', 'Misc Feature_Shed', 'Misc Feature_TenC', 'Misc Val', 'Mo Sold', 'Neighbor_int',
'Neighbor_intsorted', 'NeighborhoodClass', 'Neighborhood_Blmngtn', 'Neighborhood_Blueste', 'Neighborhood_BrDale', 'Neighborhood_BrkSide',
'Neighborhood_ClearCr', 'Neighborhood_CollgCr', 'Neighborhood_Crawfor', 'Neighborhood_Edwards', 'Neighborhood_Gilbert', 'Neighborhood_Greens',
'Neighborhood_GrnHill', 'Neighborhood_IDOTRR', 'Neighborhood_Landmrk', 'Neighborhood_MeadowV', 'Neighborhood_Mitchel', 'Neighborhood_NAmes',
'Neighborhood_NPkVill', 'Neighborhood_NWAmes', 'Neighborhood_NoRidge', 'Neighborhood_NridgHt', 'Neighborhood_OldTown', 'Neighborhood_SWISU',
'Neighborhood_Sawyer', 'Neighborhood_SawyerW', 'Neighborhood_Somerst', 'Neighborhood_StoneBr', 'Neighborhood_Timber', 'Neighborhood_Veenker',
'Open Porch SF', 'Order', 'Overall Cond', 'Overall Cond2', 'Overall Qual', 'Overall Qual2',
'PID', 'Paved Drive', 'Pool Area', 'Pool QC', 'PorchSFTotal', 'RenovationNeeded',
'Roof Matl_CompShg', 'Roof Matl_Membran', 'Roof Matl_Metal', 'Roof Matl_Roll', 'Roof Matl_Tar&Grv', 'Roof Matl_WdShake',
'Roof Matl_WdShngl', 'Roof Style_Flat', 'Roof Style_Gable', 'Roof Style_Gambrel', 'Roof Style_Hip', 'Roof Style_Mansard',
'Roof Style_Shed', 'Sale Condition_Abnorml', 'Sale Condition_AdjLand', 'Sale Condition_Alloca', 'Sale Condition_Family', 'Sale Condition_Normal',
'Sale Condition_Partial', 'Sale MonthsNo', 'Sale Type_COD', 'Sale Type_CWD', 'Sale Type_Con', 'Sale Type_ConLD',
'Sale Type_ConLI', 'Sale Type_ConLw', 'Sale Type_New', 'Sale Type_Oth', 'Sale Type_VWD', 'Sale Type_WD',
'SalePrice', 'SalePriceLog', 'Screen Porch', 'Street_Grvl', 'Street_Pave', 'TotRms AbvGrd',
'Total Bsmt SF', 'Utilities', 'Wood Deck SF', 'Year Built', 'Year Remod/Add', 'Yr Sold',

# df_numcat: 113 Spalten
# ============================================================
'1st Flr SF', '2nd Flr SF', '3Ssn Porch', 'Alley', 'Area1st2nd', 'BathroomsTotal',
'Bedroom AbvGr', 'Bldg Type', 'Bsmt Cond', 'Bsmt Exposure', 'Bsmt Full Bath', 'Bsmt Half Bath',
'Bsmt Qual', 'Bsmt Unf SF', 'BsmtFin SF 1', 'BsmtFin SF 2', 'BsmtFin Type 1', 'BsmtFin Type 2',
'Central Air', 'Condition 1', 'Condition 2', 'Electrical', 'Enclosed Porch', 'Exter Cond',
'Exter Qual', 'Exterior 1st', 'Exterior 2nd', 'Fence', 'Fireplace Qu', 'Fireplaces',
'Foundation', 'Full Bath', 'Functional', 'Garage Area', 'Garage Cars', 'Garage Cond',
'Garage Finish', 'Garage Qual', 'Garage Type', 'Garage Yr Blt', 'GarageAge', 'GarageFor2PlusCars',
'Gr Liv Area', 'Half Bath', 'Has2ndfloor', 'HasAlley', 'HasBsmt', 'HasFence',
'HasFireplace', 'HasGarage', 'HasMasVnr', 'HasPool', 'HasPorch', 'Heating',
'Heating QC', 'House Style', 'HouseAge', 'HouseIsNew', 'HouseIsRemodeled', 'HouseRemodelAge',
'IsAdjacentPositive', 'IsAdjacentRailroad', 'IsNearPositive', 'IsNearRailroad', 'IsOnArtery', 'IsOnFeedr',
'IsOnMainRoad', 'Kitchen AbvGr', 'Kitchen Bsmt', 'Kitchen Qual', 'Land Contour', 'Land Slope',
'Lot Area', 'Lot Config', 'Lot Frontage', 'Lot Shape', 'Low Qual Fin SF', 'MS SubClass',
'MS SubClass Stories', 'MS Zoning', 'Mas Vnr Area', 'Mas Vnr Type', 'Misc Feature', 'Misc Val',
'Mo Sold', 'Neighborhood', 'NeighborhoodClass', 'Open Porch SF', 'Order', 'Overall Cond',
'Overall Qual', 'PID', 'Paved Drive', 'Pool Area', 'Pool QC', 'PorchSFTotal',
'Roof Matl', 'Roof Style', 'Sale Condition', 'Sale Month', 'Sale MonthsNo', 'Sale Season',
'Sale Type', 'SalePrice', 'Screen Porch', 'Street', 'TotRms AbvGrd', 'Total Bsmt SF',
'Utilities', 'Wood Deck SF', 'Year Built', 'Year Remod/Add', 'Yr Sold',

In [19]:
# letzter Check auf fehlende Werte

# Zentrale Definition aller "fehlend"-Marker (case-insensitive)
# Marker nach Kategorien gruppiert – für die Tabelle
# Alle Marker, die geprüft werden sollen (case-insensitive)
MISSING_MARKERS = {
    '', ' ', '  ', '\t', '\n',
    'na', 'n/a', 'n.a.', 'nan',
    'none', 'null', 'nil', 'No', 'no', 'NO', 'None', 'NONE',
    '?', '-', '--', 'unknown', 'missing',
    'not available', 'not applicable',
    '<na>', 'nat', 'nicht vorhanden', 'missing'
}


def analyze_nulls_per_marker(df, name="DataFrame", show_examples=2):
    """
    Tabelle mit einer Spalte pro konkretem Marker-String.
    Spalten, die nirgends vorkommen, werden weggelassen.
    """
    # --- 1. Durchlauf: alle vorkommenden Marker sammeln ---
    used_markers = set()
    for col in df.columns:
        series = df[col]
        if series.dtype == object or pd.api.types.is_string_dtype(series.dtype):
            as_str = series.astype(str).str.strip().str.lower()
            present = set(as_str.unique()) & MISSING_MARKERS
            used_markers |= present

    # Marker sortieren: erst leer, dann alphabetisch
    def sort_key(m):
        return (m != '', m)  # leer zuerst
    used_markers_sorted = sorted(used_markers, key=sort_key)

    # --- 2. Hauptdurchlauf: pro Spalte Zählungen ---
    rows = []
    for col in df.columns:
        series = df[col]
        n_nan = int(series.isna().sum())

        is_string_col = is_object_dtype(series) or isinstance(series.dtype, pd.StringDtype)

        marker_counts = {m: 0 for m in used_markers_sorted}
        marker_examples = {m: [] for m in used_markers_sorted}

        if is_string_col:
            as_str = series.astype(str).str.strip().str.lower()
            # Nur nicht-NaN-Zeilen betrachten
            non_null_mask = ~series.isna()
            vc = as_str[non_null_mask].value_counts()
            for m in used_markers_sorted:
                cnt = int(vc.get(m, 0))
                marker_counts[m] = cnt
                if cnt > 0 and show_examples > 0:
                    # Beispiele: erste N Originalwerte, deren lower-strip == m
                    example_mask = (as_str == m) & non_null_mask
                    uniq = series[example_mask].unique()[:show_examples]
                    marker_examples[m] = [repr(u) for u in uniq]

        n_marker = sum(marker_counts.values())
        n_total = n_nan + n_marker

        if n_total == 0:
            continue

        row = {
            'Spalte': col,
            'dtype': str(series.dtype),
            'NaN': n_nan,
        }
        for m in used_markers_sorted:
            # Spaltenname: Marker-String lesbar machen
            label = f"'{m}'" if m != '' else "'' (leer)"
            row[label] = marker_counts[m]
        row['Gesamt fehlend'] = n_total
        row['% fehlend'] = round(n_total / len(df) * 100, 2)
        rows.append(row)

    if not rows:
        print(f"✅ {name}: Keine fehlenden Werte.")
        return pd.DataFrame()

    # --- 3. Spaltenreihenfolge ---
    marker_cols = []
    for m in used_markers_sorted:
        label = f"'{m}'" if m != '' else "'' (leer)"
        marker_cols.append(label)
    cols_order = ['Spalte', 'dtype', 'NaN'] + marker_cols + \
                 ['Gesamt fehlend', '% fehlend']

    result = pd.DataFrame(rows).reindex(columns=cols_order).fillna(0)
    # Zähler-Spalten als int
    for c in ['NaN'] + marker_cols + ['Gesamt fehlend']:
        result[c] = result[c].astype(int)
    result = result.sort_values('Gesamt fehlend', ascending=False).reset_index(drop=True)

    # --- 4. Zusammenfassung ---
    print(f"\n{'='*80}")
    print(f"Fehlende Werte in {name} (n={len(df)}, {len(df.columns)} Spalten)")
    print(f"{'='*80}")
    print(f"Spalten mit fehlenden Werten: {len(result)}")
    print(f"Spalten ohne fehlende Werte: {len(df.columns) - len(result)}")
    print(f"Gesamtzahl fehlender Zellen: {int(result['Gesamt fehlend'].sum())}")
    print(f"  davon NaN: {int(result['NaN'].sum())}")
    for m in used_markers_sorted:
        label = f"'{m}'" if m != '' else "'' (leer)"
        s = int(result[label].sum())
        if s > 0:
            print(f"  davon {label:20s}: {s}")
    print(f"{'='*80}")

    return result

result_num = analyze_nulls_per_marker(df_num, name="df_num")
display(result_num)    

result_numcat = analyze_nulls_per_marker(df_numcat, name="df_numcat")
display(result_numcat)

✅ df_num: Keine fehlenden Werte.

Empty DataFrame
Columns: []
Index: []

✅ df_numcat: Keine fehlenden Werte.

Empty DataFrame
Columns: []
Index: []

In [18]:
# Ausgabe von CSV für die Modellbildungen und weitere Analysen


def unique_preserve_order(seq):
    """Entfernt Duplikate, Reihenfolge bleibt erhalten."""
    seen = set()
    result = []
    for item in seq:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result



def prepare_export_columns(cols, remove_vars=None, add_vars=None,
                            saleprice_col='SalePrice'):
    cols = list(cols)
    if remove_vars:
        remove_set = set(remove_vars)
        cols = [c for c in cols if c not in remove_set]
    if add_vars:
        cols = cols + [c for c in add_vars if c not in cols]
    # Duplikate entfernen, Reihenfolge erhalten
    cols = list(unique_preserve_order(cols))
    if saleprice_col in cols:
        cols.remove(saleprice_col)
        cols.append(saleprice_col)
    return cols


# Kopie der Ausgabe von letzter Zelle für alle definierte Variablen

ALL_NUMVARS=['1st Flr SF', '2nd Flr SF', '3Ssn Porch', 'Alley', 'Area1st2nd', 'BathroomsTotal',
'Bedroom AbvGr', 'Bldg Type_1Fam', 'Bldg Type_2fmCon', 'Bldg Type_Duplex', 'Bldg Type_Twnhs', 'Bldg Type_TwnhsE',
'Bsmt Cond', 'Bsmt Exposure', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Bsmt Qual', 'Bsmt Unf SF',
'BsmtFin SF 1', 'BsmtFin SF 2', 'BsmtFin Type 1', 'BsmtFin Type 2', 'Central Air', 'Electrical',
'Enclosed Porch', 'Exter Cond', 'Exter Qual', 'Exterior 1st_AsbShng', 'Exterior 1st_AsphShn', 'Exterior 1st_BrkComm',
'Exterior 1st_BrkFace', 'Exterior 1st_CBlock', 'Exterior 1st_CemntBd', 'Exterior 1st_HdBoard', 'Exterior 1st_ImStucc', 'Exterior 1st_MetalSd',
'Exterior 1st_Plywood', 'Exterior 1st_PreCast', 'Exterior 1st_Stone', 'Exterior 1st_Stucco', 'Exterior 1st_VinylSd', 'Exterior 1st_Wd Sdng',
'Exterior 1st_WdShing', 'Exterior 2nd_AsbShng', 'Exterior 2nd_AsphShn', 'Exterior 2nd_Brk Cmn', 'Exterior 2nd_BrkFace', 'Exterior 2nd_CBlock',
'Exterior 2nd_CmentBd', 'Exterior 2nd_HdBoard', 'Exterior 2nd_ImStucc', 'Exterior 2nd_MetalSd', 'Exterior 2nd_None', 'Exterior 2nd_Other',
'Exterior 2nd_Plywood', 'Exterior 2nd_Stone', 'Exterior 2nd_Stucco', 'Exterior 2nd_VinylSd', 'Exterior 2nd_Wd Sdng', 'Exterior 2nd_Wd Shng',
'Fence', 'Fireplace Qu', 'Fireplaces', 'Foundation_BrkTil', 'Foundation_CBlock', 'Foundation_PConc',
'Foundation_Slab', 'Foundation_Stone', 'Foundation_Wood', 'Full Bath', 'Functional', 'Garage Area',
'Garage Area2', 'Garage Cars', 'Garage Cond', 'Garage Finish', 'Garage Qual', 'Garage Type_2Types',
'Garage Type_Attchd', 'Garage Type_Basment', 'Garage Type_BuiltIn', 'Garage Type_CarPort', 'Garage Type_Detchd', 'Garage Type_missing',
'Garage Yr Blt', 'GarageAge', 'GarageFor2PlusCars', 'Gr Liv Area', 'Gr Liv Area Log', 'Gr Liv Area2',
'Half Bath', 'Has2ndfloor', 'HasAlley', 'HasBsmt', 'HasFence', 'HasFireplace',
'HasGarage', 'HasMasVnr', 'HasPool', 'HasPorch', 'Heating QC', 'Heating_Floor',
'Heating_GasA', 'Heating_GasW', 'Heating_Grav', 'Heating_OthW', 'Heating_Wall', 'House Style_1.5Fin',
'House Style_1.5Unf', 'House Style_1Story', 'House Style_2.5Fin', 'House Style_2.5Unf', 'House Style_2Story', 'House Style_SFoyer',
'House Style_SLvl', 'HouseAge', 'HouseIsNew', 'HouseIsRemodeled', 'HouseRemodelAge', 'IsAdjacentPositive',
'IsAdjacentRailroad', 'IsNearPositive', 'IsNearRailroad', 'IsOnArtery', 'IsOnFeedr', 'IsOnMainRoad',
'Kitchen AbvGr', 'Kitchen Bsmt', 'Kitchen Qual', 'Land Contour', 'Land Slope', 'Lot Area',
'Lot Config', 'Lot Frontage', 'Lot Shape', 'Low Qual Fin SF', 'MS SubClass_1.5Story_PUD', 'MS SubClass_1.5Story_finished',
'MS SubClass_1.5Story_unfinished', 'MS SubClass_1Story_1945_older', 'MS SubClass_1Story_1946_newer', 'MS SubClass_1Story_PUD_1946_newer', 'MS SubClass_1Story_finished_attic', 'MS SubClass_2.5Story',
'MS SubClass_2Family_Conversion', 'MS SubClass_2Story_1945_older', 'MS SubClass_2Story_1946_newer', 'MS SubClass_2Story_PUD_1946_newer', 'MS SubClass_Duplex', 'MS SubClass_PUD_MultiLevel',
'MS SubClass_Split_Foyer', 'MS SubClass_Split_MultiLevel',  'MS Zoning_A (agr)', 'MS Zoning_C (all)', 'MS Zoning_FV',
'MS Zoning_I (all)', 'MS Zoning_RH', 'MS Zoning_RL', 'MS Zoning_RM', 'Mas Vnr Area', 'Mas Vnr Type_BrkCmn',
'Mas Vnr Type_BrkFace', 'Mas Vnr Type_CBlock', 'Mas Vnr Type_None', 'Mas Vnr Type_Stone', 'Misc Feature_Gar2', 'Misc Feature_NA',
'Misc Feature_Othr', 'Misc Feature_Shed', 'Misc Feature_TenC', 'Misc Val', 'Mo Sold', 'Neighbor_int',
'Neighbor_intsorted', 'NeighborhoodClass', 'Neighborhood_Blmngtn', 'Neighborhood_Blueste', 'Neighborhood_BrDale', 'Neighborhood_BrkSide',
'Neighborhood_ClearCr', 'Neighborhood_CollgCr', 'Neighborhood_Crawfor', 'Neighborhood_Edwards', 'Neighborhood_Gilbert', 'Neighborhood_Greens',
'Neighborhood_GrnHill', 'Neighborhood_IDOTRR', 'Neighborhood_Landmrk', 'Neighborhood_MeadowV', 'Neighborhood_Mitchel', 'Neighborhood_NAmes',
'Neighborhood_NPkVill', 'Neighborhood_NWAmes', 'Neighborhood_NoRidge', 'Neighborhood_NridgHt', 'Neighborhood_OldTown', 'Neighborhood_SWISU',
'Neighborhood_Sawyer', 'Neighborhood_SawyerW', 'Neighborhood_Somerst', 'Neighborhood_StoneBr', 'Neighborhood_Timber', 'Neighborhood_Veenker',
'Open Porch SF', 'Order', 'Overall Cond', 'Overall Cond2', 'Overall Qual', 'Overall Qual2',
'PID', 'Paved Drive', 'Pool Area', 'Pool QC', 'PorchSFTotal', 'RenovationNeeded', 'Roof Matl_CompShg',
'Roof Matl_Membran', 'Roof Matl_Metal', 'Roof Matl_Roll', 'Roof Matl_Tar&Grv', 'Roof Matl_WdShake', 'Roof Matl_WdShngl',
'Roof Style_Flat', 'Roof Style_Gable', 'Roof Style_Gambrel', 'Roof Style_Hip', 'Roof Style_Mansard', 'Roof Style_Shed',
'Sale Condition_Abnorml', 'Sale Condition_AdjLand', 'Sale Condition_Alloca', 'Sale Condition_Family', 'Sale Condition_Normal', 'Sale Condition_Partial',
'Sale MonthsNo', 'Sale Type_COD', 'Sale Type_CWD', 'Sale Type_Con', 'Sale Type_ConLD', 'Sale Type_ConLI',
'Sale Type_ConLw', 'Sale Type_New', 'Sale Type_Oth', 'Sale Type_VWD', 'Sale Type_WD', 'SalePrice',
'SalePriceLog', 'Screen Porch', 'Street_Grvl', 'Street_Pave', 'TotRms AbvGrd', 'Total Bsmt SF',
'Utilities', 'Wood Deck SF', 'Year Built', 'Year Remod/Add', 'Yr Sold']



ALL_NUMCATVARS=['1st Flr SF', '2nd Flr SF', '3Ssn Porch', 'Alley', 'Area1st2nd', 'BathroomsTotal', 'Bedroom AbvGr',
'Bldg Type', 'Bsmt Cond', 'Bsmt Exposure', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Bsmt Qual',
'Bsmt Unf SF', 'BsmtFin SF 1', 'BsmtFin SF 2', 'BsmtFin Type 1', 'BsmtFin Type 2', 'Central Air',
'Condition 1', 'Condition 2', 'Electrical', 'Enclosed Porch', 'Exter Cond', 'Exter Qual',
'Exterior 1st', 'Exterior 2nd', 'Fence', 'Fireplace Qu', 'Fireplaces', 'Foundation',
'Full Bath', 'Functional', 'Garage Area', 'Garage Cars', 'Garage Cond', 'Garage Finish',
'Garage Qual', 'Garage Type', 'Garage Yr Blt', 'GarageAge', 'GarageFor2PlusCars', 'Gr Liv Area',
'Half Bath', 'Has2ndfloor', 'HasAlley', 'HasBsmt', 'HasFence', 'HasFireplace',
'HasGarage', 'HasMasVnr', 'HasPool', 'HasPorch', 'Heating', 'Heating QC',
'House Style', 'HouseAge', 'HouseIsNew', 'HouseIsRemodeled', 'HouseRemodelAge', 'IsAdjacentPositive',
'IsAdjacentRailroad', 'IsNearPositive', 'IsNearRailroad', 'IsOnArtery', 'IsOnFeedr', 'IsOnMainRoad',
'Kitchen AbvGr', 'Kitchen Bsmt', 'Kitchen Qual', 'Land Contour', 'Land Slope', 'Lot Area',
'Lot Config', 'Lot Frontage', 'Lot Shape', 'Low Qual Fin SF', 'MS SubClass', 'MS SubClass Stories',
'MS Zoning', 'Mas Vnr Area', 'Mas Vnr Type', 'Misc Feature', 'Misc Val', 'Mo Sold',
'Neighborhood', 'NeighborhoodClass', 'Open Porch SF', 'Order', 'Overall Cond', 'Overall Qual',
'PID', 'Paved Drive', 'Pool Area', 'Pool QC', 'PorchSFTotal', 'Roof Matl', 'Roof Style',
'Sale Condition', 'Sale Type', 'Sale Month', 'Sale MonthsNo', 'Sale Season', 'SalePrice', 'Screen Porch', 'Street', 'TotRms AbvGrd',
'Total Bsmt SF', 'Utilities', 'Wood Deck SF', 'Year Built', 'Year Remod/Add', 'Yr Sold', ]

# fachlich minimale Variablenanzahl
SMALL_BASE_VARS = [
    'Order', 'PID', 
    'Lot Area', 'Gr Liv Area', 'Garage Area', 'PorchSFTotal',  'Pool Area','Total Bsmt SF',
    'Overall Qual', 'Overall Cond', 'Exter Qual', 'Kitchen Qual', 
    'BathroomsTotal',
    'Year Built', 'Year Remod/Add',
    'IsNearRailroad', 'IsAdjacentRailroad', 'IsNearPositive', 'IsAdjacentPositive',
    'NeighborhoodClass',
    'Sale Condition_Abnorml', 'Sale Condition_AdjLand', 'Sale Condition_Alloca', 'Sale Condition_Family', 'Sale Condition_Normal', 'Sale Condition_Partial', 
    'Sale Type_COD', 'Sale Type_CWD', 'Sale Type_Con', 'Sale Type_ConLD', 'Sale Type_ConLI', 'Sale Type_ConLw','Sale Type_New','Sale Type_Oth', 'Sale Type_VWD', 
    'Sale Type_WD',
    'MS SubClass_1.5Story_PUD', 'MS SubClass_1.5Story_finished', 'MS SubClass_1.5Story_unfinished', 'MS SubClass_1Story_1945_older',
    'MS SubClass_1Story_1946_newer', 'MS SubClass_1Story_PUD_1946_newer', 'MS SubClass_1Story_finished_attic', 'MS SubClass_2.5Story', 'MS SubClass_2Family_Conversion', 'MS SubClass_2Story_1945_older',
    'MS SubClass_2Story_1946_newer', 'MS SubClass_2Story_PUD_1946_newer', 'MS SubClass_Duplex', 'MS SubClass_PUD_MultiLevel', 'MS SubClass_Split_Foyer', 'MS SubClass_Split_MultiLevel',
    'MS Zoning_A (agr)', 'MS Zoning_C (all)', 'MS Zoning_FV', 'MS Zoning_I (all)', 'MS Zoning_RH', 'MS Zoning_RL', 'MS Zoning_RM',
    'SalePrice'
]


DROP_FIRST_RAREST_VARS = [
    'Bldg Type_2fmCon', # 62 Häuser, Mittel 125 682 $
    'Exterior 1st_CBlock',
    'Exterior 2nd_CBlock',
    'Foundation_Wood',
    'Garage Type_CarPort',
    'Heating_Floor',
    'House Style_2.5Fin',
    'Mas Vnr Type_CBlock',  # 1 Häuser, Mittel 80 000$
    'Misc Feature_Othr',  # 4 Häuser, Mittel 155 625$
    'MS SubClass_1.5Story_PUD',
    'MS Zoning_A (agr)',
    'Neighborhood_Blueste', # 10 Häuser, Mittel 143 590 $
    'Roof Matl_Roll',  # 1 Häuser, Mittel 137 000 $
    'Roof Style_Shed',
    'Sale Type_Con',
    'Sale Condition_AdjLand',
]
DROP_FIRST_MOST_FREQUENT_VARS = [  # Intercept ist stabil und interpretierbar; Koeffizienten sind echte Abschläge/Aufschläge.
    'Bldg Type_1Fam', 
    'House Style_1Story',
    'Exterior 1st_VinylSd',
    'Exterior 2nd_VinylSd',
    'Foundation_PConc',
    'Garage Type_Attchd',
    'Heating_GasA',
    'Mas Vnr Type_BrkFace', 
    'MS SubClass_1Story_1946_newer',
    'MS Zoning_RL',
    'Misc Feature_NA',  
    'Neighborhood_NAmes', 
    'Roof Matl_CompShg',  
    'Roof Style_Gable',
    'Sale Type_WD',
    'Sale Condition_Normal',
]

TRANSFORM_NUM_VARS = [
    'Overall Qual2',
    'Overall Cond2',
    'Garage Area2',
    'Gr Liv Area Log', 
    'Gr Liv Area2',
    'MS SubClass_num',
    'Neighbor_int', 'Neighbor_intsorted', 'NeighborhoodClass',
    'SalePriceLog', 
]
TRANSFORM_CAT_VARS = [
    'Sale Month', 'Sale MonthsNo', 'Sale Season',
]

NEW_NUMVARS = [
    'Area1st2nd', 'BathroomsTotal',
    'GarageAge', 'GarageFor2PlusCars',
    'Has2ndfloor', 'HasAlley', 'HasBsmt', 'HasFence', 'HasFireplace', 'HasGarage', 'HasMasVnr', 'HasPool', 'HasPorch',
    'HouseAge', 'HouseIsNew','HouseIsRemodeled', 'HouseRemodelAge',
    'Kitchen Bsmt',
    'Neighbor_int', 'Neighbor_intsorted', 'NeighborhoodClass',
    'IsAdjacentPositive', 'IsAdjacentRailroad','IsNearPositive', 'IsNearRailroad','IsOnArtery', 'IsOnFeedr', 'IsOnMainRoad',
    'PorchSFTotal',
    'RenovationNeeded',
    'Total Bsmt SF',
]


UNIMPORTANT_VARS = [
    'Alley', 
    'Fence', 'Fireplace Qu', 'GarageAge',                                                           
    'HouseAge', 'HouseIsNew','HouseIsRemodeled', 'HouseRemodelAge',                                                             
    'IsAdjacentPositive', 'IsAdjacentRailroad','IsNearPositive', 'IsNearRailroad','IsOnArtery', 'IsOnFeedr',
    'Lot Frontage', 'Mas Vnr Type', 'Misc Feature_Gar2',  
    'Overall Qual',  # nur wewnn Overall Qual2 angefügt wird
    'Paved Drive', 
    'Pool QC','Misc Feature',
]

LEAKAGE_VARS = [
    'Mo Sold', 'Yr Sold', 'Sale MonthsNo',
    'Sale Condition', 'Sale Condition_Abnorml', 'Sale Condition_AdjLand', 'Sale Condition_Alloca', 'Sale Condition_Family', 'Sale Condition_Normal', 'Sale Condition_Partial',
    # 'NeighborhoodClass', 'Neighborhoodint', 'Neighborhoodint_sorted'  weil Saleprice verwendet wird
]

DATAFRAME_REGISTRY = {
    'df_num':    df_num,
    'df_numcat': df_numcat,
}
# ==================================================
# Zentrale Definition: Welche Datei enthält welche Spalten?
# ==================================================

CSV_EXPORTS = [
    ('Ames_Num_Small_DropFirst.csv',           'df_num', prepare_export_columns(SMALL_BASE_VARS,  remove_vars=DROP_FIRST_MOST_FREQUENT_VARS)),
    ('Ames_Num_Small_DropRarestFirst.csv',     'df_num', prepare_export_columns(SMALL_BASE_VARS,  remove_vars=DROP_FIRST_RAREST_VARS)),
    ('Ames_Num_Small.csv',                     'df_num', prepare_export_columns(SMALL_BASE_VARS)),
    ('Ames_Num_Small_Transform_DropFirst.csv', 'df_num', prepare_export_columns(SMALL_BASE_VARS, remove_vars=DROP_FIRST_MOST_FREQUENT_VARS, add_vars=TRANSFORM_NUM_VARS)),
    ('Ames_Num_Best_DropFirst.csv',            'df_num', prepare_export_columns(ALL_NUMVARS, remove_vars=DROP_FIRST_MOST_FREQUENT_VARS + TRANSFORM_NUM_VARS + UNIMPORTANT_VARS + LEAKAGE_VARS,
                                                                                add_vars=['Overall Qual2'])),
    ('Ames_NumCat_Best.csv',                   'df_numcat', prepare_export_columns(ALL_NUMCATVARS, remove_vars= TRANSFORM_NUM_VARS + UNIMPORTANT_VARS + LEAKAGE_VARS)),
    ('Ames_EDA_Num.csv',                       'df_num', prepare_export_columns(ALL_NUMVARS)),
    ('Ames_EDA_NumCat.csv',                    'df_numcat', prepare_export_columns(ALL_NUMCATVARS+TRANSFORM_CAT_VARS)),
]

# --------------------------------------------------
# Zusätzliche Dateien — nur zur Anzeige, kein Export
# --------------------------------------------------

EXTRA_FILES = [
    'AmesHousing.csv',
]



# ==================================================
# Hilfsfunktion: Spaltenliste für Export vorbereiten
# ==================================================

# ==================================================
# CSV-Export mit Fortschrittsausgabe
# ==================================================

print("=" * 78)
print("CSV-Export")
print("=" * 78)

# --------------------------------------------------
# Duplikat-Check einmalig vorab
# --------------------------------------------------
for fname, source_name, cols in CSV_EXPORTS:
    if len(cols) != len(set(cols)):
        dupes = sorted({c for c in cols if cols.count(c) > 1})
        print(f"⚠️  {fname}: Duplikate in Spaltenliste: {dupes}")

# --------------------------------------------------
# Eigentlicher Export
# --------------------------------------------------
_export_summary = []

for fname, source_name, cols in CSV_EXPORTS:
    source_df = DATAFRAME_REGISTRY[source_name]

    # Sicherheits-Check: fehlende Spalten
    missing = [c for c in cols if c not in source_df.columns]
    if missing:
        print(f"⚠️  {fname}: {len(missing)} Spalten fehlen in {source_name}")
        print(f"     Fehlend: {missing[:10]}{'...' if len(missing) > 10 else ''}")
        cols = [c for c in cols if c in source_df.columns]

    if not cols:
        print(f"❌ {fname}: keine gültigen Spalten – Datei wird übersprungen.")
        continue

    source_df[cols].to_csv(fname, index=False)
    n_rows = len(source_df)
    n_cols = len(cols)
    print(f"✅ {fname:<45s} {n_cols:>4d} Spalten × {n_rows:>5d} Zeilen")
    _export_summary.append((fname, n_cols, n_rows))

# --------------------------------------------------
# Zusammenfassung
# --------------------------------------------------
print()
print(f"Insgesamt {len(_export_summary)} Datei(en) geschrieben.")
print("=" * 78)


# ==================================================
# Variablen-Datei-Matrix — vollständig dynamisch
# ==================================================

import os
import re
import pandas as pd
import panel as pn

pn.extension('tabulator')


# ==================================================
# 1. Hilfsfunktionen
# ==================================================

def short_name(filename, prefix='Ames_', suffix='.csv'):
    """Entfernt Präfix und Suffix aus einem Dateinamen."""
    name = str(filename).strip()
    if prefix and name.startswith(prefix):
        name = name[len(prefix):]
    if suffix and name.endswith(suffix):
        name = name[:-len(suffix)]
    return name.strip()



def wildcard_to_regex(pattern):
    """Wildcard-Muster mit '*' → Regex. Case-insensitive."""
    pattern = (pattern or '').strip()
    if not pattern:
        return None
    regex_body = re.escape(pattern).replace(r'\*', '.*')
    if '*' not in pattern:
        regex_body = f".*{regex_body}.*"
    elif pattern.endswith('*') and not pattern.startswith('*'):
        regex_body = f"^{regex_body}"
    elif pattern.startswith('*') and not pattern.endswith('*'):
        regex_body = f"{regex_body}$"
    return re.compile(regex_body, re.IGNORECASE)


def estimate_width(col_name, min_width=100, max_width=400, char_px=10, padding=40):
    """Schätzt eine sinnvolle Spaltenbreite anhand der Namenslänge."""
    col_name = str(col_name).strip()
    estimated = len(col_name) * char_px + padding
    return max(min_width, min(estimated, max_width))


def read_csv_header(path):
    """Liest die Spaltennamen einer CSV-Datei (nur Header)."""
    try:
        header = pd.read_csv(path, nrows=0).columns.tolist()
        return [str(c).strip() for c in header]
    except Exception as e:
        print(f"⚠️  Fehler beim Lesen von '{path}': {e}")
        return None


def dtype_to_str(dtype):
    """Formatiert einen pandas-dtype als kurzen String."""
    if dtype is None:
        return '—'
    name = str(dtype)
    name = name.replace('datetime64[ns]', 'datetime')
    name = name.replace('timedelta64[ns]', 'timedelta')
    return name


def get_dtype_info(df, col):
    """Liefert einen kurzen Datentyp-String für eine Spalte."""
    if df is None or col not in df.columns:
        return '—'
    return dtype_to_str(df[col].dtype)


# ==================================================
# 2. Dateiliste zusammenbauen
# ==================================================

file_definitions = {}

# --- Zusätzliche Dateien (nur zur Anzeige) ---
extra_file_names = []   # wird für die Spaltenreihenfolge gebraucht
for extra_file in EXTRA_FILES:
    if os.path.exists(extra_file):
        cols = read_csv_header(extra_file)
        if cols is not None:
            file_definitions[extra_file] = cols
            extra_file_names.append(extra_file)
            print(f"✅ Zusätzliche Datei gefunden und eingelesen: "
                  f"{extra_file} ({len(cols)} Spalten)")
    else:
        print(f"ℹ️  Zusätzliche Datei nicht gefunden: "
              f"{extra_file} (wird übersprungen)")

# --- Export-Dateien aus CSV_EXPORTS ---
export_file_names = []
print("=" * 78)
for entry in CSV_EXPORTS:
    if len(entry) == 3:
        fname, source_name, cols = entry
    else:
        fname, cols = entry
        source_name = 'df_num'   # Fallback

    fname_clean = fname.strip()
    file_definitions[fname_clean] = [
        str(c).strip() for c in unique_preserve_order(cols)
    ]
    export_file_names.append(fname_clean)

# ==================================================
# Übersicht: Anzahl Spalten je Datei
# ==================================================

# Zusätzliche Dateien (nur Anzeige)
if extra_file_names:
    print("\nZusätzliche Dateien (nur Anzeige, kein Export):")
    for fname in extra_file_names:
        print(f"  {fname:<45s} {len(file_definitions[fname]):>4d} Variablen")

# Gesamtzahl eindeutiger Variablen
all_vars = set()
for cols in file_definitions.values():
    all_vars.update(cols)
print("\nGesamtzahl eindeutiger Variablen über alle Dateien:")
print(f"  {len(all_vars):>6} Variablen")

print("\nVariablen pro DataFrame:")
for name, df_obj in [('df', df), ('df_num', df_num), ('df_numcat', df_numcat)]:
    print(f"  {name:<10}: {len(df_obj.columns):>6} Variablen")

all_df_vars = set(df.columns) | set(df_num.columns) | set(df_numcat.columns)
print(f"\nEindeutige Variablen über df, df_num, df_numcat: {len(all_df_vars):>6} Variablen")


# Export-Dateien
if export_file_names:
    print("\nExport-Dateien:")
    for fname in export_file_names:
        print(f"  {fname:<45s} {len(file_definitions[fname]):>4d} Variablen")


# ==================================================
# 3. Kurznamen automatisch ableiten
# ==================================================

short_headers = {
    fname: short_name(fname).strip()
    for fname in file_definitions
}

seen_short_names = {}
for fname, short in short_headers.items():
    if short in seen_short_names:
        print(f"⚠️  Kurznamen-Kollision: '{short}' von '{fname}' "
              f"und '{seen_short_names[short]}'")
    seen_short_names[short] = fname


# ==================================================
# 4. Spaltenbreiten und -reihenfolge
# ==================================================
# Reihenfolge:
#   1. Variable
#   2. EXTRA_FILES (z. B. AmesHousing) — erste Spalte(n) nach Variable
#   3. DType_Org, DType_Num, DType_Cat
#   4. CSV_EXPORTS-Dateien
# ==================================================

COLUMN_WIDTHS = {
    'Variable':   140,
    'DType_Org':  110,
    'DType_Num':  110,
    'DType_Cat':  110,
}

# Extra-Dateien zuerst (nach Variable)
for fname in extra_file_names:
    col = short_headers[fname]
    COLUMN_WIDTHS[col] = estimate_width(col)

# DType-Spalten und Export-Dateien
for fname in export_file_names:
    col = short_headers[fname]
    COLUMN_WIDTHS[col] = estimate_width(col)

# Endgültige Spaltenreihenfolge
COLUMN_ORDER = (
    ['Variable']
    + [short_headers[f] for f in extra_file_names]                 # ← AmesHousing zuerst
    + ['DType_Org', 'DType_Num', 'DType_Cat']
    + [short_headers[f] for f in export_file_names]
)

TABLE_WIDTH = sum(COLUMN_WIDTHS[col] for col in COLUMN_ORDER)
TABLE_DISPLAY_WIDTH = 1100          # ← hier die gewünschte Breite in px
TABLE_DISPLAY_HEIGHT = 400          # ← Höhe in px (vertikales Scrollen)

# ==================================================
# 5. Matrix aufbauen
# ==================================================

all_referenced_vars = sorted(
    set().union(*[set(v) for v in file_definitions.values()])
)

rows = []
for var in all_referenced_vars:
    var_clean = str(var).strip()

    # Datentypen ermitteln
    dtype_org = get_dtype_info(df_org, var_clean) if 'df_org' in globals() else '—'
    dtype_num = get_dtype_info(df_num, var_clean) if 'df_num' in globals() else '—'
    dtype_cat = get_dtype_info(df_numcat, var_clean) if 'df_numcat' in globals() else '—'

    row = {
        'Variable':  var_clean,
        'DType_Org': dtype_org,
        'DType_Num': dtype_num,
        'DType_Cat': dtype_cat,
    }

    # Datei-Spalten
    for fname in file_definitions:
        col = short_headers[fname]
        row[col] = 'x' if var_clean in file_definitions[fname] else ''

    rows.append(row)

df_files = pd.DataFrame(rows)

# Spalten in die gewünschte Reihenfolge bringen
# (nur Spalten, die tatsächlich existieren)
ordered_existing_cols = [c for c in COLUMN_ORDER if c in df_files.columns]
df_files = df_files[ordered_existing_cols]

# Spaltennamen strippen
df_files.columns = [str(c).strip() for c in df_files.columns]

# Alphabetisch nach Variable sortieren (Groß-/Kleinschreibung ignorieren)
df_files = df_files.sort_values(
    'Variable', key=lambda s: s.str.casefold()
).reset_index(drop=True)

# Werte als String
for col in df_files.columns:
    df_files[col] = df_files[col].fillna('').astype(str)


# ==================================================
# 6. Filter-Widgets — eine pro Spalte
# ==================================================

filter_widgets = {}

# Variable-Filter
filter_widgets['Variable'] = pn.widgets.TextInput(
    placeholder='Filter (Wildcards * erlaubt)',
    width=COLUMN_WIDTHS['Variable'] - 10,
    margin=(0, 5, 0, 0),
    styles={'font-size': '11px'},
)

# DType-Filter
for dtype_col in ['DType_Org', 'DType_Num', 'DType_Cat']:
    filter_widgets[dtype_col] = pn.widgets.TextInput(
        placeholder='z. B. int, float, object',
        width=COLUMN_WIDTHS[dtype_col] - 10,
        margin=(0, 5, 0, 0),
        styles={'font-size': '11px'},
    )

# Datei-Filter (extra + export)
for fname in extra_file_names + export_file_names:
    col = short_headers[fname]
    filter_widgets[col] = pn.widgets.TextInput(
        placeholder='x',
        width=COLUMN_WIDTHS[col] - 10,
        margin=(0, 5, 0, 0),
        styles={'font-size': '11px'},
    )


# ==================================================
# 7. Reaktiver Tabulator
# ==================================================
filter_widgets_ordered = {col: filter_widgets[col] for col in COLUMN_ORDER}
# ==================================================
# 6. Reaktiver Tabulator mit Header-Filtern
# ==================================================
# Header-Filter scrollen automatisch mit der Tabelle mit.
# frozen_columns=['Variable'] wirkt jetzt, weil der Tabulator
# selbst (nicht der äußere Container) horizontal scrollt.

# ==================================================
# 6. Tabulator mit Header-Filtern (nicht reaktiv nötig)
# ==================================================
# Header-Filter filtern clientseitig im Browser — kein Python-Callback.
# frozen_columns wirkt, weil der Tabulator selbst scrollt.

def build_table():
    return pn.widgets.Tabulator(
        df_files,
        pagination=None,
        height=TABLE_DISPLAY_HEIGHT,
        width=TABLE_DISPLAY_WIDTH,
        show_index=False,
        header_align='left',
        text_align='left',
        frozen_columns=['Variable'],
        widths=COLUMN_WIDTHS,
        sorters=[{'field': 'Variable', 'dir': 'asc'}], 
        header_filters={
            'Variable':   {'type': 'input', 'func': 'like',
                           'placeholder': 'Filter'},
            'DType_Org':  {'type': 'input', 'func': 'like',
                           'placeholder': 'int/float/object'},
            'DType_Num':  {'type': 'input', 'func': 'like',
                           'placeholder': 'int/float/object'},
            'DType_Cat':  {'type': 'input', 'func': 'like',
                           'placeholder': 'int/float/object'},
            **{short_headers[f]: {'type': 'input', 'func': 'like',
                                  'placeholder': 'x'}
               for f in extra_file_names + export_file_names},
        },
        styles={'font-size': '12px', 'font-family': 'Arial, sans-serif'},
        configuration={
            'columnDefaults': {
                'headerWordWrap': True,
                'headerVertical': False,
                'resizable': True,
                'sorter': 'string',
                'sorterParams': {'locale': True}, 
            },
            'tooltipsHeader': True,
            'layout': 'fitData',
            'scrollX': True,
            'scrollY': True,
        },
    )


# ==================================================
# 7. Layout
# ==================================================
layout = pn.Column(
    pn.pane.Markdown("### Welche Variablen sind in welcher Datei?"),
    pn.pane.Markdown(
        "**Filter stehen in den Spaltenköpfen** und scrollen mit.  \n"
        "Variable & DTypes: Substring-Suche (`area`, `int`, …)  \n"
        "Datei-Spalten: `x` eingeben → nur Zeilen, die in dieser Datei sind"
    ),
    build_table(),        # ← direkt aufrufen, nicht als Referenz übergeben
    width=TABLE_DISPLAY_WIDTH + 20,
)

# layout ans Ende verschoben, damit Juypter dies ausgibt


# ==================================================
# DIAGNOSE: Variablen-Zählung und Export-Konsistenz
# ==================================================
import ast, textwrap, os, sys

# --------------------------------------------------
# Quellcode + AST-Parsing
# --------------------------------------------------
def _get_source():
    """Best effort: Quellcode der aktuellen Datei/Zelle holen."""
    fpath = globals().get('__file__')
    if fpath and os.path.exists(fpath):
        try:
            with open(fpath, 'r', encoding='utf-8') as f:
                return f.read(), fpath
        except Exception:
            pass
    try:
        import inspect
        mod = sys.modules.get('__main__')
        if mod and getattr(mod, '__file__', None):
            return inspect.getsource(mod), mod.__file__
    except Exception:
        pass
    try:
        import IPython
        ip = IPython.get_ipython()
        if ip is not None:
            for cell in reversed(list(ip.history_manager.input_hist_parsed)):
                if 'CSV_EXPORTS' in cell and 'prepare_export_columns' in cell:
                    return cell, '<IPython history>'
    except Exception:
        pass
    return None, None


def _ast_label(node):
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        return f"{_ast_label(node.left)} + {_ast_label(node.right)}"
    if isinstance(node, ast.List):
        vals = [el.value for el in node.elts if isinstance(el, ast.Constant)]
        return '[' + ', '.join(repr(v) for v in vals) + ']'
    return '<Ausdruck>'


def _subset_entries(node):
    if isinstance(node, ast.Name):
        return [('names', node.id, [node.id])]
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        return _subset_entries(node.left) + _subset_entries(node.right)
    if isinstance(node, ast.List):
        vals = [el.value for el in node.elts if isinstance(el, ast.Constant)]
        label = '[' + ', '.join(repr(v) for v in vals) + ']'
        return [('literals', label, vals)]
    return [('literals', '<Ausdruck>', [])]


def _extract_recipes(src):
    tree = ast.parse(textwrap.dedent(src))
    target = None
    for node in ast.walk(tree):
        if isinstance(node, (ast.Assign, ast.AnnAssign)):
            tgt = node.targets[0] if isinstance(node, ast.Assign) else node.target
            if isinstance(tgt, ast.Name) and tgt.id == 'CSV_EXPORTS' \
               and isinstance(node.value, ast.List):
                target = node.value
                break
    if target is None:
        return None
    out = {}
    for elt in target.elts:
        if not isinstance(elt, ast.Tuple) or len(elt.elts) < 3:
            continue
        fnode = elt.elts[0]
        if not (isinstance(fnode, ast.Constant) and isinstance(fnode.value, str)):
            continue
        fname = fnode.value
        call = elt.elts[2]
        if not (isinstance(call, ast.Call) and isinstance(call.func, ast.Name)
                and call.func.id == 'prepare_export_columns'):
            out[fname] = None
            continue
        rcp = {'basis_label': None, 'basis_names': [],
               'remove': [], 'add': []}
        if call.args:
            rcp['basis_label'] = _ast_label(call.args[0])
            bnames = _subset_entries(call.args[0])
            for kind, _, payload in bnames:
                if kind == 'names':
                    rcp['basis_names'].extend(payload)
                else:
                    rcp['basis_names'].extend(payload)
        for kw in call.keywords:
            if kw.arg == 'remove_vars':
                rcp['remove'].extend(_subset_entries(kw.value))
            elif kw.arg == 'add_vars':
                rcp['add'].extend(_subset_entries(kw.value))
        out[fname] = rcp
    return out


def _resolve(kind, payload):
    """Teilmengen-Payload in Werte umwandeln."""
    if kind == 'names':
        return _vals_for(payload)
    return list(unique_preserve_order(payload))


def _vals_for(names):
    """Bezeichner gegen globals() auflösen, Duplikate entfernen."""
    out = []
    for nm in names:
        out.extend(globals().get(nm, []))
    return unique_preserve_order(out)


def _print_miss(miss_set, indent='          ', label='verfehlt',
                width=110):
    """Verfehlte Variablen vollständig ausgeben, umbrochen auf
    mehrere Zeilen. Keine Kürzung."""
    items = sorted(miss_set)
    if not items:
        print(f"{indent}{label}: —")
        return
    body = ', '.join(items)
    first_prefix = f"{indent}{label}: "
    cont_prefix  = indent + ' ' * (len(label) + 2)
    wrapped = textwrap.wrap(
        body,
        width=width,
        initial_indent=first_prefix,
        subsequent_indent=cont_prefix,
        break_long_words=False,
        break_on_hyphens=False,
    )
    for line in wrapped:
        print(line)


# --------------------------------------------------
# 1) Konstanten — Anzahl Variablen
# --------------------------------------------------
print("=" * 78)
print("1) Konstanten — Anzahl Variablen")
print("=" * 78)

def _describe_const(name, seq):
    seq = list(seq)
    uniq = unique_preserve_order(seq)
    dupes = sorted({x for x in seq if seq.count(x) > 1})
    print(f"  {name:<32s} total={len(seq):>4d}  "
          f"unique={len(uniq):>4d}  dupes={len(dupes)}")
    if dupes:
        print(f"    ⚠️  Duplikate: {dupes}")

_constants = [
    'ALL_NUMVARS', 'ALL_NUMCATVARS', 'SMALL_BASE_VARS',
    'DROP_FIRST_RAREST_VARS', 'DROP_FIRST_MOST_FREQUENT_VARS',
    'TRANSFORM_NUM_VARS', 'TRANSFORM_CAT_VARS',
    'NEW_NUMVARS', 'UNIMPORTANT_VARS', 'LEAKAGE_VARS',
]
for _name in _constants:
    _obj = globals().get(_name)
    if _obj is None:
        print(f"  {_name:<32s} (nicht definiert)")
        continue
    _describe_const(_name, _obj)

# --------------------------------------------------
# 2) Quellcode auswerten
# --------------------------------------------------
_src, _src_origin = _get_source()
_recipes = _extract_recipes(_src) if _src else None

# --------------------------------------------------
# 3) Pro Exportdatei: Treffer / Verfehlt pro Teilmenge
# --------------------------------------------------
print()
print("=" * 78)
print("2) Treffer/Verfehlt pro Exportdatei und Teilmenge")
print("=" * 78)

_issues = []

for _entry in CSV_EXPORTS:
    _fname, _src_df, _cols = (_entry if len(_entry) == 3
                              else (_entry[0], 'df_num', _entry[1]))

    # Spaltenzahlen
    _cols = list(_cols)
    _uniq = unique_preserve_order(_cols)
    _dupes = sorted({c for c in _cols if _cols.count(c) > 1})
    _sdf = DATAFRAME_REGISTRY.get(_src_df)
    _missing = ([c for c in _uniq if c not in _sdf.columns]
                if _sdf is not None else [])
    _exportable = ([c for c in _uniq if c in _sdf.columns]
                   if _sdf is not None else _uniq)

    print()
    print(f"── {_fname}")
    print(f"   Quelle: {_src_df}   "
          f"dekl={len(_cols)}  unique={len(_uniq)}  "
          f"fehlt={len(_missing)}  export={len(_exportable)}")

    if _dupes:
        print(f"   ⚠️  Duplikate: {_dupes}")
        _issues.append(f"{_fname}: Duplikate {_dupes}")
    if _missing:
        print(f"   ⚠️  Fehlt in '{_src_df}': {_missing}")
        _issues.append(f"{_fname}: {len(_missing)} fehlend in {_src_df}")
    if 'SalePrice' in _exportable and _exportable[-1] != 'SalePrice':
        print("   ⚠️  SalePrice nicht letzte Spalte")
        _issues.append(f"{_fname}: SalePrice nicht zuletzt")

    rcp = _recipes.get(_fname) if _recipes else None
    if rcp is None:
        if _recipes is not None:
            print("   ℹ️  Rezept nicht aus Quelle extrahierbar.")
        continue

    # Basis
    basis_set = set(_vals_for(rcp['basis_names']))
    if rcp['basis_label']:
        print(f"   Basis  : {rcp['basis_label']:<50s} "
              f"unique={len(basis_set)}")

        # remove_vars: pro Teilmenge EIGENE Zeile
    if rcp['remove']:
        print("   remove_vars:")
    for kind, lbl, payload in rcp['remove']:
        vals = _resolve(kind, payload)
        vals_set = set(vals)
        hit = vals_set & basis_set
        miss = vals_set - basis_set
        flag = '⚠️ ' if miss else '   '
        print(f"     {flag}{lbl}")
        print(f"          trifft={len(hit):>3d}/{len(vals_set):<3d}  "
              f"verfehlt={len(miss):>3d}")
        if hit:
            _print_miss(hit, label='trifft')
        if miss:
            _print_miss(miss, label='verfehlt')
            _issues.append(
                f"{_fname} / {lbl}: {len(miss)} verfehlt "
                f"({', '.join(sorted(miss))})"
            )

    # add_vars: pro Teilmenge EIGENE Zeile
    if rcp['add']:
        removed_set = set()
        for kind, _, payload in rcp['remove']:
            removed_set.update(_resolve(kind, payload))

    for kind, lbl, payload in rcp['add']:
        vals = _resolve(kind, payload)
        vals_set = set(vals)
        in_basis      = vals_set & basis_set
        not_in_basis  = vals_set - basis_set
        was_removed   = in_basis & removed_set
        stayed        = in_basis - removed_set
        effective_new = not_in_basis | was_removed

        print(f"      {lbl}")
        print(f"          n={len(vals_set):<3d}  "
              f"neu effektiv={len(effective_new):<3d}  "
              f"zurückgeholt={len(was_removed):<3d}  "
              f"war schon drin={len(stayed):<3d}  "
              f"nie in Basis={len(not_in_basis)}")
        if was_removed:
            _print_miss(was_removed, label='zurückgeholt')
        if stayed:
            _print_miss(stayed, label='war schon drin')
        if not_in_basis:
            _print_miss(not_in_basis, label='nie in Basis')
# --------------------------------------------------
# 4) Gesamtübersicht
# --------------------------------------------------
print()
print("=" * 78)
print("3) Gesamtübersicht")
print("=" * 78)


# Rendering von layout sicherstellen (da oben print gelaufen ist)
layout

==============================================================================
CSV-Export
==============================================================================
✅ Ames_Num_Small_DropFirst.csv                    56 Spalten ×  2925 Zeilen
✅ Ames_Num_Small_DropRarestFirst.csv              56 Spalten ×  2925 Zeilen
✅ Ames_Num_Small.csv                              60 Spalten ×  2925 Zeilen
✅ Ames_Num_Small_Transform_DropFirst.csv          65 Spalten ×  2925 Zeilen
✅ Ames_Num_Best_DropFirst.csv                    206 Spalten ×  2925 Zeilen
✅ Ames_NumCat_Best.csv                            88 Spalten ×  2925 Zeilen
✅ Ames_EDA_Num.csv                               257 Spalten ×  2925 Zeilen
✅ Ames_EDA_NumCat.csv                            113 Spalten ×  2925 Zeilen

Insgesamt 8 Datei(en) geschrieben.
==============================================================================

✅ Zusätzliche Datei gefunden und eingelesen: AmesHousing.csv (82 Spalten)
==============================================================================

Zusätzliche Dateien (nur Anzeige, kein Export):
  AmesHousing.csv                                 82 Variablen

Gesamtzahl eindeutiger Variablen über alle Dateien:
     280 Variablen

Variablen pro DataFrame:
  df        :     82 Variablen
  df_num    :    258 Variablen
  df_numcat :    113 Variablen

Eindeutige Variablen über df, df_num, df_numcat:    280 Variablen

Export-Dateien:
  Ames_Num_Small_DropFirst.csv                    56 Variablen
  Ames_Num_Small_DropRarestFirst.csv              56 Variablen
  Ames_Num_Small.csv                              60 Variablen
  Ames_Num_Small_Transform_DropFirst.csv          65 Variablen
  Ames_Num_Best_DropFirst.csv                    206 Variablen
  Ames_NumCat_Best.csv                            88 Variablen
  Ames_EDA_Num.csv                               257 Variablen
  Ames_EDA_NumCat.csv                            113 Variablen
==============================================================================
1) Konstanten — Anzahl Variablen
==============================================================================
  ALL_NUMVARS                      total= 257  unique= 257  dupes=0
  ALL_NUMCATVARS                   total= 113  unique= 113  dupes=0
  SMALL_BASE_VARS                  total=  60  unique=  60  dupes=0
  DROP_FIRST_RAREST_VARS           total=  16  unique=  16  dupes=0
  DROP_FIRST_MOST_FREQUENT_VARS    total=  16  unique=  16  dupes=0
  TRANSFORM_NUM_VARS               total=  10  unique=  10  dupes=0
  TRANSFORM_CAT_VARS               total=   3  unique=   3  dupes=0
  NEW_NUMVARS                      total=  31  unique=  31  dupes=0
  UNIMPORTANT_VARS                 total=  21  unique=  21  dupes=0
  LEAKAGE_VARS                     total=  10  unique=  10  dupes=0

==============================================================================
2) Treffer/Verfehlt pro Exportdatei und Teilmenge
==============================================================================

── Ames_Num_Small_DropFirst.csv
   Quelle: df_num   dekl=56  unique=56  fehlt=0  export=56
   Basis  : SMALL_BASE_VARS                                    unique=60
   remove_vars:
     ⚠️ DROP_FIRST_MOST_FREQUENT_VARS
          trifft=  4/16   verfehlt= 12
          trifft: MS SubClass_1Story_1946_newer, MS Zoning_RL, Sale Condition_Normal, Sale Type_WD
          verfehlt: Bldg Type_1Fam, Exterior 1st_VinylSd, Exterior 2nd_VinylSd, Foundation_PConc, Garage
                    Type_Attchd, Heating_GasA, House Style_1Story, Mas Vnr Type_BrkFace, Misc Feature_NA,
                    Neighborhood_NAmes, Roof Matl_CompShg, Roof Style_Gable

── Ames_Num_Small_DropRarestFirst.csv
   Quelle: df_num   dekl=56  unique=56  fehlt=0  export=56
   Basis  : SMALL_BASE_VARS                                    unique=60
   remove_vars:
     ⚠️ DROP_FIRST_RAREST_VARS
          trifft=  4/16   verfehlt= 12
          trifft: MS SubClass_1.5Story_PUD, MS Zoning_A (agr), Sale Condition_AdjLand, Sale Type_Con
          verfehlt: Bldg Type_2fmCon, Exterior 1st_CBlock, Exterior 2nd_CBlock, Foundation_Wood, Garage
                    Type_CarPort, Heating_Floor, House Style_2.5Fin, Mas Vnr Type_CBlock, Misc Feature_Othr,
                    Neighborhood_Blueste, Roof Matl_Roll, Roof Style_Shed

── Ames_Num_Small.csv
   Quelle: df_num   dekl=60  unique=60  fehlt=0  export=60
   Basis  : SMALL_BASE_VARS                                    unique=60

── Ames_Num_Small_Transform_DropFirst.csv
   Quelle: df_num   dekl=65  unique=65  fehlt=0  export=65
   Basis  : SMALL_BASE_VARS                                    unique=60
   remove_vars:
     ⚠️ DROP_FIRST_MOST_FREQUENT_VARS
          trifft=  4/16   verfehlt= 12
          trifft: MS SubClass_1Story_1946_newer, MS Zoning_RL, Sale Condition_Normal, Sale Type_WD
          verfehlt: Bldg Type_1Fam, Exterior 1st_VinylSd, Exterior 2nd_VinylSd, Foundation_PConc, Garage
                    Type_Attchd, Heating_GasA, House Style_1Story, Mas Vnr Type_BrkFace, Misc Feature_NA,
                    Neighborhood_NAmes, Roof Matl_CompShg, Roof Style_Gable
      TRANSFORM_NUM_VARS
          n=10   neu effektiv=9    zurückgeholt=0    war schon drin=1    nie in Basis=9
          war schon drin: NeighborhoodClass
          nie in Basis: Garage Area2, Gr Liv Area Log, Gr Liv Area2, MS SubClass_num, Neighbor_int,
                        Neighbor_intsorted, Overall Cond2, Overall Qual2, SalePriceLog

── Ames_Num_Best_DropFirst.csv
   Quelle: df_num   dekl=206  unique=206  fehlt=0  export=206
   Basis  : ALL_NUMVARS                                        unique=257
   remove_vars:
        DROP_FIRST_MOST_FREQUENT_VARS
          trifft= 16/16   verfehlt=  0
          trifft: Bldg Type_1Fam, Exterior 1st_VinylSd, Exterior 2nd_VinylSd, Foundation_PConc, Garage
                  Type_Attchd, Heating_GasA, House Style_1Story, MS SubClass_1Story_1946_newer, MS Zoning_RL,
                  Mas Vnr Type_BrkFace, Misc Feature_NA, Neighborhood_NAmes, Roof Matl_CompShg, Roof
                  Style_Gable, Sale Condition_Normal, Sale Type_WD
     ⚠️ TRANSFORM_NUM_VARS
          trifft=  9/10   verfehlt=  1
          trifft: Garage Area2, Gr Liv Area Log, Gr Liv Area2, Neighbor_int, Neighbor_intsorted,
                  NeighborhoodClass, Overall Cond2, Overall Qual2, SalePriceLog
          verfehlt: MS SubClass_num
     ⚠️ UNIMPORTANT_VARS
          trifft= 19/21   verfehlt=  2
          trifft: Alley, Fence, Fireplace Qu, GarageAge, HouseAge, HouseIsNew, HouseIsRemodeled,
                  HouseRemodelAge, IsAdjacentPositive, IsAdjacentRailroad, IsNearPositive, IsNearRailroad,
                  IsOnArtery, IsOnFeedr, Lot Frontage, Misc Feature_Gar2, Overall Qual, Paved Drive, Pool QC
          verfehlt: Mas Vnr Type, Misc Feature
     ⚠️ LEAKAGE_VARS
          trifft=  9/10   verfehlt=  1
          trifft: Mo Sold, Sale Condition_Abnorml, Sale Condition_AdjLand, Sale Condition_Alloca, Sale
                  Condition_Family, Sale Condition_Normal, Sale Condition_Partial, Sale MonthsNo, Yr Sold
          verfehlt: Sale Condition
      ['Overall Qual2']
          n=1    neu effektiv=1    zurückgeholt=1    war schon drin=0    nie in Basis=0
          zurückgeholt: Overall Qual2

── Ames_NumCat_Best.csv
   Quelle: df_numcat   dekl=88  unique=88  fehlt=0  export=88
   Basis  : ALL_NUMCATVARS                                     unique=113
   remove_vars:
     ⚠️ TRANSFORM_NUM_VARS
          trifft=  1/10   verfehlt=  9
          trifft: NeighborhoodClass
          verfehlt: Garage Area2, Gr Liv Area Log, Gr Liv Area2, MS SubClass_num, Neighbor_int,
                    Neighbor_intsorted, Overall Cond2, Overall Qual2, SalePriceLog
     ⚠️ UNIMPORTANT_VARS
          trifft= 20/21   verfehlt=  1
          trifft: Alley, Fence, Fireplace Qu, GarageAge, HouseAge, HouseIsNew, HouseIsRemodeled,
                  HouseRemodelAge, IsAdjacentPositive, IsAdjacentRailroad, IsNearPositive, IsNearRailroad,
                  IsOnArtery, IsOnFeedr, Lot Frontage, Mas Vnr Type, Misc Feature, Overall Qual, Paved Drive,
                  Pool QC
          verfehlt: Misc Feature_Gar2
     ⚠️ LEAKAGE_VARS
          trifft=  4/10   verfehlt=  6
          trifft: Mo Sold, Sale Condition, Sale MonthsNo, Yr Sold
          verfehlt: Sale Condition_Abnorml, Sale Condition_AdjLand, Sale Condition_Alloca, Sale
                    Condition_Family, Sale Condition_Normal, Sale Condition_Partial

── Ames_EDA_Num.csv
   Quelle: df_num   dekl=257  unique=257  fehlt=0  export=257
   Basis  : ALL_NUMVARS                                        unique=257

── Ames_EDA_NumCat.csv
   Quelle: df_numcat   dekl=113  unique=113  fehlt=0  export=113
   Basis  : ALL_NUMCATVARS + TRANSFORM_CAT_VARS                unique=113

==============================================================================
3) Gesamtübersicht
==============================================================================

Column(width=1120)
    [0] Markdown(str)
    [1] Markdown(str)
    [2] Tabulator(frozen_columns=['Variable'], header_align='left', header_filters={'Variable': {'type': 'inp...}, height=400, show_index=False, sizing_mode='fixed', sorters=[{'field': 'Variable', ...], styles={'font-size': '12px', ...}, text_align='left', value=              ..., width=1100, widths={'Variable': 140, ...})